### ISSUE TITLE
Should ?protons and ?neutrons be public parameters to teachers?

### ISSUE THREAD

**Issue by zepumph** [phetsims/build-a-nucleus#101]
We aren't sure at today's design meeting, but will think about it! Mostly we want to make sure that screen 2 behaves well for too large of atoms.

**Comment by zepumph** [comment]
Let's first test things out, for example reentry happens for screen 2 with http://localhost:8080/build-a-nucleus/build-a-nucleus_en.html?brand=phet&ea&debugger&protons=55&neutrons=57&screens=2

**Comment by zepumph** [comment]
- [x] We should also add CT tests that test with those query parameters

**Comment by zepumph** [comment]
This is no longer failing, and I got rid of the setTimeout by  using `isConstructionCompleteProperty`. I'm not sure if there is a better way to validate this, or error. But now on the second screen it will just max out the nucleus if the query parameter is more than is available. 

- [x] We should still add validation to the query parameter given a total sim max.
UPDATE: see https://github.com/phetsims/build-a-nucleus/blob/7ab1b740045d3af7f56660ccb4f2e0197daa1ae4/js/common/BANQueryParameters.ts#L21

**Comment by zepumph** [comment]
Up next, we just want to touch base with a designer about the current behavior on the second screen. You can still specify way too many particles for that screen, and it will just be incorrect, but maxed out.

**Comment by zepumph** [comment]
- [x] Just have these parameters effect the decay screen
- [x] Rename to `decayScreenProtons`
- [x] make public and update documentation
- [x] Add `chartScreenProtons` for the second screen (with its own validation for its available particle counts).
- [ ] Make sure the `decayScreenProtons` and `decayScreenNeutrons` parameter gets into the teacher tips.

**Comment by zepumph** [comment]
@Luisav1 and I decided it made sense to have chartScreenProtons (and neutrons) as public and in teacher tips too.

**Comment by zepumph** [comment]
Working on this now.

**Comment by zepumph** [comment]
Alright we now have 4 query parameters which work something like this:

http://localhost:8080/build-a-nucleus/build-a-nucleus_en.html?brand=phet&ea&debugger&decayScreenProtons=92&decayScreenNeutrons=145&chartIntroScreenProtons=5&chartIntroScreenNeutrons=4


the chart screen values are capped at their screens nuclide counts (10 and 12). The only thing left to do is to make sure these get into teach tips. Over to @arouinfar  to make sure that happens or to assign someone else if I got it wrong.

**Comment by arouinfar** [comment]
Love these query parameters! Seems like the only remaining work is to document in the Teacher Tips. I've added this to the tracking issue #128 so we can close this one.
