### ISSUE TITLE
Beryllium-8 alpha decay shows incorrect number of particles in miniParticleAtom

### ISSUE THREAD

**Issue by Luisav1** [phetsims/build-a-nucleus#109]
An alpha decay on Beryllium-8 should result in 2 protons and 2 neutrons but the mini particle shows 3 protons and 3 neutrons.
Before decay:
![image](https://github.com/phetsims/build-a-nucleus/assets/52978048/b2786389-c6fb-4f6a-ba82-3087ef0a3a31)
After decay:
![image](https://github.com/phetsims/build-a-nucleus/assets/52978048/708da2fe-b092-4dd9-91ee-823df24a048f)

The alpha particle is correctly emitted however (a particle with 2 protons and 2 neutrons is shown flying off).

I noticed that removing the call to `removeParticle()` in the `particleAtom.extractParticle( particleType )` function fixed this temporarily, but it doesn't completely work since the particles extracted must be removed. So, I believe the extra mini particles must be appearing due to a listener on one of the particle arrays.

**Comment by zepumph** [comment]
Fixed about with @Luisav1.
