### ISSUE TITLE
DecayModel.halfLifeNumberProperty doesn't support "unknown" half lives

### ISSUE THREAD

**Issue by zepumph** [phetsims/build-a-nucleus#111]
Found while handling a TODO in https://github.com/phetsims/build-a-nucleus/issues/93. If unknown, then that Property should be `null` (from AtomIdentifier), but that isn't supported or expected from its TypeScript implementation.

**Comment by zepumph** [comment]
It isn't clear what the desired behavior is for the halfLifeNumberProperty when it reaches unknown. @Luisav1 let me know if you want assistance on this.

**Comment by Luisav1** [comment]
If the half-life is null (aka "unknown") then the half-life is set to -1 when the `halfLifeNumberProperty` is set.
https://github.com/phetsims/build-a-nucleus/blob/f2b033adf90e18792a3fa241befcf6c4c86a8753/js/decay/model/DecayModel.ts#L51-L54

Then this is dealt with appropiatly in the listener:
https://github.com/phetsims/build-a-nucleus/blob/74f8279f12a9469e770392edb7c4d5f9aea54737/js/decay/view/HalfLifeNumberLineNode.ts#L268-L276

The use of -1 as a placeholder can be done in `AtomIdentifier` instead though like below, is this something we want to do?
```js
  // Get the half-life of a nuclide with the specified number of protons and neutrons.
  getNuclideHalfLife: function( numProtons: number, numNeutrons: number ): number | null | undefined {
    if ( !HalfLifeConstants[ numProtons ] ) {
      return undefined;
    }
    else if ( HalfLifeConstants[ numProtons ][ numNeutrons ] === null ) {
      return -1;
    }
    return HalfLifeConstants[ numProtons ][ numNeutrons ];
  },
```

**Comment by zepumph** [comment]
I think the issue to solve here is that the terms `undefined` and `null` are codified values that mean something, but are not documented. I believe that the work to be done is to document the possible results returned by the function (a half life number, no half life, or an unknown half life), and then the corresponding code values of each. I think of it as a bug that `undefined` and `null` mean two different things, and I think that `-1` would do a good job of representing an unknown half life. 

Also if you would like my response or assistance on an issue please re-assign me so I don't lose it (which I am very good at doing).

**Comment by zepumph** [comment]
Discussed with @Luisav1, let's also change null -> -1 in HalfLifeConstants too.

* Update doc
* remove the mapping from null -> -1 in the getter function.

**Comment by zepumph** [comment]
After finding this data `null = unknown` duplicated in the DECAYS_INFO_TABLE as well, I think it may just be easiest to keep things as is. Closing
