### ISSUE TITLE
Element name and half-life doesn't follow the arrow in the half-life dialog

### ISSUE THREAD

**Issue by Luisav1** [phetsims/build-a-nucleus#117]
In the [public version](https://phet.colorado.edu/sims/html/build-a-nucleus/latest/build-a-nucleus_all.html), the half-life text follows the arrow in the half-life dialog like so:
![image](https://github.com/phetsims/build-a-nucleus/assets/52978048/15e055aa-3661-479f-9472-a4e432513694)

But in the latest [dev version](https://phet-dev.colorado.edu/html/build-a-nucleus/1.0.0-dev.20/phet/build-a-nucleus_all_phet.html), the half-life text stays on the left side.
![image](https://github.com/phetsims/build-a-nucleus/assets/52978048/702395a2-af45-4a29-9c86-0da82e59ba2c)

**Comment by Luisav1** [comment]
This https://github.com/phetsims/build-a-nucleus/commit/0e7e6585260470ecf5e71c30047fd0ed3f6e0091 removed the animation of the half-life text to support dynamic layout but I'm unsure how to have a property on the text again to keep track of its x value.

**Comment by zepumph** [comment]
I think this is fixed now, please test with http://localhost:8080/build-a-nucleus/build-a-nucleus_en.html?brand=phet&ea&debugger&locales=*&keyboardLocaleSwitcher&stringTest=dynamic to use arrow keys to dynamically change the text to ensure it updates into the right position.

**Comment by Luisav1** [comment]
This is fixed now and works great, thanks @zepumph! Closing.
