### ISSUE TITLE
Memory test

### ISSUE THREAD

**Issue by Luisav1** [phetsims/build-a-nucleus#119]
From self code review https://github.com/phetsims/build-a-nucleus/issues/112.

**Comment by Luisav1** [comment]
On-hold because of CT issue #129.

**Comment by zepumph** [comment]
https://github.com/phetsims/build-a-nucleus/issues/129 is closed. let's do it!

**Comment by jbphet** [comment]
As part of the code review in https://github.com/phetsims/build-a-nucleus/issues/165 I ran a memory test.  There is a screenshot of the results below.  The bottom line is that there may be a slow leak, but nothing egregious, and what we do see could be explainable by pooling in Scenery.

Everything was done in a Chrome incognito window using a freshly built version of `build-a-nucleus_all_phet_debug.html`.

Explanation:
- Snapshot 1 - loaded, no interaction
- Snapshot 2 - after a minute of basic interaction, then a reset on both screens and a return to the home screen
- Snapshot 3 - after a reload with the `fuzz` parameter added and one minute of fuzzing
- Snapshots 4 thru 12 - snapshots at one minute intervals while fuzzing
- Snapshot 13 - Stopped fuzzing using `phet.chipper.queryParameter.fuzz = false`, reset both screens, went to the home screen

![image](https://github.com/phetsims/build-a-nucleus/assets/3082831/2bd513e2-03f2-4af9-8c5c-9a8c655fc455)

**Comment by zepumph** [comment]
When I create 10 of each nucleon and then reset, the comparison memory tool doesn't show any obvious memory leaks. Yay!

**Comment by zepumph** [comment]
We found one problem with how we were recreating a Text, PatternStringProperty, AND a DerivedProperty each time the mass number changed. Oops. Fixed here.

**Comment by zepumph** [comment]
After fuzzing for 45 minutes and capturing snapshots intermittently, I don't see problems anymore. Woo! Closing. Thanks @Luisav1 for all your help.

![image](https://github.com/phetsims/build-a-nucleus/assets/6856943/c29224f7-b632-446d-ac55-df0160151b11)

**Comment by zepumph** [comment]
Arg! Found another nested listener adding:

https://github.com/phetsims/build-a-nucleus/blob/1475dedc07ee8c6227610432c6faa485ea105afb/js/common/view/NucleonNumberPanel.ts#L110-L121

**Comment by zepumph** [comment]
`?listenerLimit=1000` has been helpful for this nesting issue

**Comment by zepumph** [comment]
After fuzzing for a while I saw that the maxListenerCount was 783, then when I restarted the sim with ?listenerLimit=782, it failed on startup. No further work to be done here.
