### ISSUE TITLE
Some nuclides are unstable but do not have a known decay path

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/build-a-nucleus#12]
Fore example Yb 150 (70 protons and 80 neutrons) has a known half-life but not a currently known decay path. We may want to consider how to deal with cases like this with some sort of note displayed about an unknown decay path.

For the prototype we will just display the half-life but no decays will be available.

**Comment by Luisav1** [comment]
This was addressed with an info button on the Available Decays panel. Marking for design meeting to see if @ariel-phet wants to do anything more.

**Comment by zepumph** [comment]
From design meeting 7/13. We are happy with using the term "unknown" and will proceed with that. Closing
