### ISSUE TITLE
Update credits

### ISSUE THREAD

**Issue by Luisav1** [phetsims/build-a-nucleus#123]
Credits already added but update them if necessary. From self code review in https://github.com/phetsims/build-a-nucleus/issues/112.

**Comment by zepumph** [comment]
@KatieWoe we are ready for QA credits as we move into final RC spot check.

**Comment by KatieWoe** [comment]
Credits should add Jaron Droder

**Comment by zepumph** [comment]
Committed and cherry picked into 1.1

**Comment by zepumph** [comment]
Feel free

**Comment by zepumph** [comment]
From https://github.com/phetsims/qa/issues/994#issuecomment-1761967645, we should add @marlitas and @zepumph to the dev credits. Thanks @Nancy-Salpepi

**Comment by zepumph** [comment]
Cherry picked to the 1.1 branch. Closing

**Comment by Luisav1** [comment]
I talked with Jason this morning and will add a thanks to the CNS (Canadian Nuclear Society) for funding the sim too.

**Comment by Luisav1** [comment]
Added thanks to the CNS in the main branch and in 1.1. Closing.
