### ISSUE TITLE
Translations may need to be updated

### ISSUE THREAD

**Issue by Luisav1** [phetsims/build-a-nucleus#125]
Translations may need to be updated, using a script most likely as will be done here https://github.com/phetsims/build-a-nucleus/issues/76#issuecomment-1666186403, since in the currently published version, the legend item strings in the Half-life Info dialog had the dash "-" which is now removed and done in the code instead. This fix was done for https://github.com/phetsims/build-a-nucleus/issues/76 in this commit https://github.com/phetsims/build-a-nucleus/commit/8cae8de53cde01d66ae453c79a1ae51b823db3e5.
This was found while doing the self code review in #112.

**Comment by zepumph** [comment]
Thanks for reporting! This is important, and I definitely could have forgotten to clean this up. Thanks you! The script over in https://github.com/phetsims/build-a-nucleus/issues/76#issuecomment-1683069139 will also fix this problem.
