### ISSUE TITLE
Items to include in Teacher Tips

### ISSUE THREAD

**Issue by zepumph** [phetsims/build-a-nucleus#128]
From a conversation with @Luisav1, this seems to be the only desired change to have Magic Numbers be explained in the Teacher Tips. I don't think I'm describing it too well, but I wanted to capture it in a github issue.

**Comment by Luisav1** [comment]
Thanks, @zepumph. Yes, from a conversation on slack, it's okay that the connection between magic numbers and stability was not made:
Luisa Vargas
  [1:22 PM](https://phetsims.slack.com/archives/D022EPEFJJ3/p1691522572250489)
Hey Ariel, we had 2 interviews on Friday that went really well. Here are the notes on it for each of the students. Based on these, AR doesn't think we need to do more interviews and neither do I. What do you think though?


Ariel Paul
  [8:08 AM](https://phetsims.slack.com/archives/D022EPEFJJ3/p1691590098125569)
Hey Luisa, I would agree more interviews probably not necessary. Sim seems to be working well. It seems the only thing is students might not be getting the connection of magic numbers to stability, but I think that is OK, probably a pretty advanced learning goal with no prior knowledge, so not really a concern.

- [x] note the difference and the significance of 'outer' vs 'inner' nucleons (which are not interactive) through particles being closer together and farther away on their energy levels

**Comment by arouinfar** [comment]
The Pages template used for Teacher Tips is found here: [sim-name-guide.pages](https://o365coloradoedu.sharepoint.com/sites/PHYS-phet-pilot/PhET%20Files/Forms/AllItems.aspx?id=%2Fsites%2FPHYS%2Dphet%2Dpilot%2FPhET%20Files%2FPhET%20Files%2FPhET%20Teaching%20Resources%2FTeacher%20Tips%2FHTML5%20Teacher%20Tips%20templates&viewid=3aa550f4%2Df9ef%2D4871%2Dbcb3%2Da192486a9aaa)

- [x] Document all relevant query parameters, both common code and those created in #101. 
   - [x] `decayScreenNeutrons`
   - [x] `decayScreenProtons`
   - [x] `chartIntroScreenNeutrons`
   - [x] `chartIntroScreenProtons`
   - [x] `screens`
   - [x] `initialScreen`
   - [x]  `locale`
   - [x] `allowLinks`
   - [x] `supportsPanAndZoom`

**Comment by arouinfar** [comment]
@Luisav1 created the Teacher Tips, then I edited and uploaded to SharePoint and the website, closing.
