### ISSUE TITLE
Prefer IReadOnlyProperty to DerivedProperty for type annotations

### ISSUE THREAD

**Issue by samreid** [phetsims/build-a-nucleus#13]
From discussion in our TypeScript slack channel.  It will be clearer to write some of the `DerivedProperty` type annotations as `IReadOnlyProperty`.  For instance:

```ts
class HalfLifeInformationNode extends Node {

  constructor( halfLifeNumberProperty: DerivedProperty<number,
                 [ protonCount: number, neutronCount: number, doesNuclideExist: boolean, isStable: boolean ]>,
               isStableBooleanProperty: DerivedProperty<boolean, [ protonCount: number, neutronCount: number ]> ) {
    super();
```

would be preferable to change to:

```ts
class HalfLifeInformationNode extends Node {

  constructor( halfLifeNumberProperty: IReadOnlyProperty<number>,
               isStableBooleanProperty: IReadOnlyProperty<boolean> ) {
    super();
```

This code does not need to know how the Property is derived, or what its dependencies are.  It only needs to know that it can observe the changes.

Same with code like this in BANModel:

```ts
public isStableBooleanProperty: DerivedProperty<boolean, [ protonCount: number, neutronCount: number ]>;
public readonly massNumberProperty: DerivedProperty<number, [ protonCount: number, neutronCount: number ]>;
public readonly doesNuclideExistBooleanProperty: DerivedProperty<boolean, [ protonCount: number, neutronCount: number ]>;
```

**Comment by samreid** [comment]
Thanks, nice fixes @Luisav1.

**Comment by Luisav1** [comment]
No problem, thanks @samreid for the suggestions. I agree it reads clearer now.

**Comment by samreid** [comment]
I opened https://github.com/phetsims/axon/issues/391 for the more general problem, in my opinion this issue can be closed.  Anyone feel free to reopen for any reason.
