### ISSUE TITLE
BANConstants has many positioning and size constants that can be derived

### ISSUE THREAD

**Issue by Luisav1** [phetsims/build-a-nucleus#135]
From #112.
- [x] the center of the atom screen view coordinates could be based on layout bounds, include the layout bounds from the screenView in BANConstants.
- [x] the distance between energy levels can be based on the width of the energy levels

For an example, follow BAMConstants.
```js
  // center of the atom in view coordinates
  SCREEN_VIEW_ATOM_CENTER_X: 335,
  SCREEN_VIEW_ATOM_CENTER_Y: 339,

  // the x distance between the left side of the nucleon energy levels
  X_DISTANCE_BETWEEN_ENERGY_LEVELS: 255,
```

**Comment by zepumph** [comment]
I couldn't find any others. Will you spot check and let me know if any others should be changed?

Also, I found that in the constants file an alpha value was being set to 200. I changed it to 1 (the max). Please update to .8 if you meant for it to be 200/255.

**Comment by Luisav1** [comment]
I compared it with the published version and it seems the max values should be used. I didn't find any other values that should be changed either. Thanks @zepumph, closing this issue now.
