### ISSUE TITLE
removeParticle from BANScreenView can be move to BANModel and renamed

### ISSUE THREAD

**Issue by Luisav1** [phetsims/build-a-nucleus#138]
From #112.
removeParticle in BANScreenView only removes the particle from the model particle arrays so it can be move to BANModel. 

BANModel already has a removeParticle function that removes particle's from the `particles` array. So a rename and maybe an investigation into why there are so many `removeParticle` functions would be good to do.

**Comment by zepumph** [comment]
@Luisav1 and I simplified the removeParticle() logic so now there is just a function on the model, and ParticleAtom (plus some overrides). We like this better than having things in the screen view. Closing
