### ISSUE TITLE
Move restorePreviousNucleonNumber and removeNucleonImmediatelyFromAtom from view to model

### ISSUE THREAD

**Issue by Luisav1** [phetsims/build-a-nucleus#142]
From #112. `restorePreviousNucleonNumber()` and `removeNucleonImmediatelyFromAtom()` in DecayScreenView both only have model components so they can be moved to DecayModel.

**Comment by zepumph** [comment]
`removeNucleonImmediatelyFromAtom` uses `animateAndRemoveParticle`, so let's keep these in the view. I'll make them prototype functions though and see if we like that.
