### ISSUE TITLE
Decay buttons and particle labels in AvailableDecaysPanel could each be their own class

### ISSUE THREAD

**Issue by Luisav1** [phetsims/build-a-nucleus#146]
From #112.
The decay buttons and their enabled properties can be its own class, as well as the particle labels that go with each decay button.
These are already currently created separately (within the same AvailableDecays constructor) and then joined via a VBox.

**Comment by zepumph** [comment]
While that is true, that is a large portion of that class which is less than 200 lines. First I'd like to play with just moving some stuff to methods from the constructor.

**Comment by zepumph** [comment]
I basically did a bit of a code review + refactoring on AvailableDecaysPanel and this is what I came up with. I don't recommend factioring out buttons into their own classes. Will you please review and I'm happy to discuss any next steps you'd like to do.

**Comment by Luisav1** [comment]
This is looking much cleaner, thanks @zepumph. Closing.
