### ISSUE TITLE
Pass in only particleAtom.positition value to isNucleonInCaptureArea()

### ISSUE THREAD

**Issue by Luisav1** [phetsims/build-a-nucleus#149]
From #112. Currently passing in entire particleAtom.

**Comment by zepumph** [comment]
I do not think this is necessary, see https://github.com/phetsims/build-a-nucleus/issues/152#issuecomment-1684419690

**Comment by zepumph** [comment]
@Luisav1 and I discussed and are in agreement.

**Comment by zepumph** [comment]
Just kidding, we liked @Luisav1's idea here, because it was so simple and much cleaner.
