### ISSUE TITLE
../../../build-a-nucleus/js/decay/view/DecayScreenView.ts(426,29): error TS2339: Property 'changeNucleonType' does not exist on type 'ParticleAtom'.

### ISSUE THREAD

**Issue by samreid** [phetsims/build-a-nucleus#15]
CT has been showing this type error for a while:

> ../../../build-a-nucleus/js/decay/view/DecayScreenView.ts(426,29): error TS2339: Property 'changeNucleonType' does not exist on type 'ParticleAtom'.

I tried to find the cause, but it is unclear.  I'm going to band-aid it with a ts-ignore for now.

**Comment by chrisklus** [comment]
Thanks @samreid - this is clear on CT, closing.
