### ISSUE TITLE
Pass in only extractParticle() function to emitNucleon

### ISSUE THREAD

**Issue by Luisav1** [phetsims/build-a-nucleus#152]
From #112.

**Comment by zepumph** [comment]
This is a reasonable thought, but I kinda think it is more trouble than it is worth. Much of the worry in regards to "only pass in what you need" is for class constructors, where by passing in a whole model class, you are more likely to use other stuff that further breaks encapsulation and muddy the exact purpose of your class. Here, it seems totally fine to provide a particleAtom to a function for extracting one of its particles. 

I recommend closing this issue as a wontfix, but I'm happy to discuss further.

**Comment by zepumph** [comment]
@Luisav1 and I discussed and are in agreement.
