### ISSUE TITLE
DecayEquationModel only needs the cellModellArray[ protonNumber ] row instead of the whole cellModelArray

### ISSUE THREAD

**Issue by Luisav1** [phetsims/build-a-nucleus#154]
From #112.

**Comment by zepumph** [comment]
I'm not sure that is true, because we link to updates whenever the protonNumber changes. Should we just keep things as is? 

https://github.com/phetsims/build-a-nucleus/blob/475e3eebcb4a365cff2880cf8318f45f1b5d8f36/js/chart-intro/model/DecayEquationModel.ts#L39-L40

**Comment by Luisav1** [comment]
Yes that makes sense. Things should be kept as is. Thanks @zepumph. Closing.
