### ISSUE TITLE
branch: betaDecay

### ISSUE THREAD

**Issue by chrisklus** [phetsims/build-a-nucleus#16]
This branch is to support changes on the build-a-nucleus branch of shred. It will be deleted once merged to master. Errors causing https://github.com/phetsims/build-a-nucleus/issues/15 have been moved to the branch.

**Comment by Luisav1** [comment]
Closing since the build-a-nucleus branch in shred was deleted.

**Comment by zepumph** [comment]
This was used for some one-offs it looks like, but we don't need to make any more of those. Closing.
