### ISSUE TITLE
Half life text jumps when arrow animates from infinity back to a number

### ISSUE THREAD

**Issue by zepumph** [phetsims/build-a-nucleus#162]
@Luisav1 reported, and I think that this is from the VBox work for dynamic locale of in #102.

**Comment by Luisav1** [comment]
Reopening because this still happens when you reset the sim after being at an infinity half-life number. For example, resetting on Hydrogen - 2 (1p 1n).

**Comment by zepumph** [comment]
Ahh! Thanks. How about this?

**Comment by Luisav1** [comment]
Looks great, thanks! Closing.
