### ISSUE TITLE
'Unstable' is not shown for neutrons. Do we want this?

### ISSUE THREAD

**Issue by Luisav1** [phetsims/build-a-nucleus#163]
Not sure if this is a bug or on purpose and if so how come we don't show it?
https://github.com/phetsims/build-a-nucleus/blob/9385abf655e86824c8e75436ac37230866165595/js/decay/view/StabilityIndicatorText.ts#L42-L54

**Comment by Luisav1** [comment]
The above commit shows stability for when only neutrons are present too. But we want to double-check with @ariel-phet that is behaviour we want.

**Comment by zepumph** [comment]
@ariel-phet and I discussed this, and found https://en.wikipedia.org/wiki/Neutron, with this:

>A free neutron is unstable, [decaying](https://en.wikipedia.org/wiki/Free_neutron_decay) to a proton

This means that @Luisav1 fixed a bug above, and not just a pedagogical error. Thanks!
