### ISSUE TITLE
Consider adding labels to the full nucleus stability chart

### ISSUE THREAD

**Issue by jbphet** [phetsims/build-a-nucleus#168]
There is a button in the "Chart Intro" screen that brings up a modal dialog containing a full chart of nucleus stabilities.  There are no labels on the axes of this chart, which I recall being a pet peeve of one of my former teachers.  When I click on the "Full Chart" link in this dialog, a web page is opened that shows an interactive version of the chart _with labels_ on the axes.  However, PhET sims are sometimes used in environments where outside internet access isn't available, so students might not be able to access the click-thru version of the chart.  Thus, I think it would be good to have labels on the chart that is available within the sim.

Full chart from sim:

![image](https://github.com/phetsims/build-a-nucleus/assets/3082831/4a1585a7-387c-4a5b-950e-2fa17e78e0d4)

Full chart from external link available in the sim:

![image](https://github.com/phetsims/build-a-nucleus/assets/3082831/d845524e-909c-42d6-ae74-8ba1b0d844f4)

This came up during code review, see https://github.com/phetsims/build-a-nucleus/issues/165.

**Comment by zepumph** [comment]
I like the idea! Let's see what @Luisav1 thinks.

**Comment by zepumph** [comment]
In addition to this work, @Luisav1 was talking to Jason and they may be changing the colors in the full chart app anyways. Let's wait for that to happen before taking a new screenshot. Don't forget to update the notes of the license over in https://github.com/phetsims/build-a-nucleus/issues/180 with what it takes to get the new screenshot (more details is better!).

**Comment by zepumph** [comment]
@Luisav1, what is the current status of this issue?

**Comment by Luisav1** [comment]
The screenshot still has a little black stroke on the right that needs to be removed.
![image](https://github.com/phetsims/build-a-nucleus/assets/52978048/4ec19f7c-f117-47c8-be94-e40795ccfe6d)
Update the screenshot and then close.

**Comment by Luisav1** [comment]
The screenshot now shows the full nuclide chart with matching colors to the sim and axis labels as well. Closing.
