### ISSUE TITLE
doesNuclideExistBooleanProperty should be false for p0n0

### ISSUE THREAD

**Issue by zepumph** [phetsims/build-a-nucleus#169]
While working on a few cleanup steps over in https://github.com/phetsims/build-a-nucleus/issues/164, @Luisav1 and I found that the sim is quite dependent on a "hack" of sorts that makes p0n0 nucleus an existent atom. This is a falsehood, and so we should try to fix this assumption.

**Comment by zepumph** [comment]
After many hours and a few extra rabbit holes, @Luisav1 and I have successfully removed the hackary which stated that p0n0 existed and had an unknown halflife. Commit coming soon.

**Comment by zepumph** [comment]
Ok, that was a lot! It would be great to keep this open in case CT or others find trouble with the enabled buttons. I also think it would be a good thing to bring to a dev test to make sure that QA hammers on the enabled buttons.

For QA to test:
* Confirm no regressions (correct behavior) of the enabled-ness of the buttons and the particle createorNodes 
* Confirm good behavior with all logic centered around an empty atom (going to it and from it).

Feel free to close

**Comment by Nancy-Salpepi** [comment]
Things look OK to me in dev.23. Will keep this open for @KatieWoe to confirm as well.

**Comment by KatieWoe** [comment]
I haven't seen anything either
