### ISSUE TITLE
Clean up violations of the 120 column width recommendation

### ISSUE THREAD

**Issue by jbphet** [phetsims/build-a-nucleus#176]
Our `coding-conventions.md` document says, "Generally, lines should not exceed 120 columns. Break up long statements, expressions...".  I'm running into a lot of violations of this recommendation, and it makes it tricky for people like me with older eyes who have to use larger fonts.  I'd recommend making a pass through the code and cleaning this up a bit.  Some violations are reasonable, but I've seen quite a few already in the handful of files that I've looked at.

Here is an example:

![image](https://github.com/phetsims/build-a-nucleus/assets/3082831/19c4cdf3-dd55-4baa-a1e1-865cbfb1d87f)

![image](https://github.com/phetsims/build-a-nucleus/assets/3082831/bdf787a9-c8f0-4ab8-afaf-b951331337cb)

**Comment by zepumph** [comment]
@Luisav1 can you please take the lead on this?

**Comment by Luisav1** [comment]
Thanks @jbphet! This was all fixed in the commits above. Closing.
