### ISSUE TITLE
Dynamically changing locales causes inconsistent radio button sizes

### ISSUE THREAD

**Issue by jbphet** [phetsims/build-a-nucleus#178]
Found during code review, see #165.

When the locale is changed dynamically it can cause the radio button sizes to be inconsistent.  There are a couple of screenshots below to illustrate.  This is a know common code issue, see https://github.com/phetsims/sun/issues/852, but I thought I should log it so that the designer can decide how important it is to get this fixed before publication.

To illustrate, here is an example of the "Available Decays" panel when launched with `locale=de` (German):

![image](https://github.com/phetsims/build-a-nucleus/assets/3082831/e5ea4139-d1ac-49df-b532-088f1b0ce4ef)

Here's what this panel looks like if launched with `locales=*` and then the locale is changed to Deutsch (German):

![image](https://github.com/phetsims/build-a-nucleus/assets/3082831/a461fb46-39fa-4102-a535-712fd108da18)

**Comment by jbphet** [comment]
Here are a couple of other examples that look a bit worse.

Kurdish:

![image](https://github.com/phetsims/build-a-nucleus/assets/3082831/92174012-d58d-4e9c-b311-46b0620cad2d)

French:

![image](https://github.com/phetsims/build-a-nucleus/assets/3082831/a9ee38fe-fe2d-42bb-a655-67b0d07af045)

**Comment by jbphet** [comment]
Assigning to the people that I think did the design to prioritize this.  They can pass it on as appropriate.

**Comment by zepumph** [comment]
@Luisav1 and I would like to pair on this so she can get a glimpse at some of the i18n dynamic locale work.

**Comment by Luisav1** [comment]
@zepumph and I fixed this in the commit above. Closing.
