### ISSUE TITLE
Update the README file

### ISSUE THREAD

**Issue by jbphet** [phetsims/build-a-nucleus#181]
From code review, see #165.

The README file appears to be out of date, and says the sim is unpublished, but I think it's been published as a prototype and is about to be published as a full sim, so it's time to make this real.

**Comment by zepumph** [comment]
I believe this is automatically done in `grunt production`. These are auto generated from templates, and shouldn't be edited directly (which I think you know, but just confirming).

**Comment by zepumph** [comment]
Yes, since this line is only done during `grunt production` and not during a prototype (and that seems correct to me), I recommend no changes.
