### ISSUE TITLE
Consider changing name of `ParticleNucleus` class

### ISSUE THREAD

**Issue by jbphet** [phetsims/build-a-nucleus#183]
Related to #165.

The name of the `ParticleNucleus` class in, IMO, misleading and it cost me some time when trying to understand some portions of the code.  The term "nucleus" is defined (in the Webster dictionary) as "a central point, group, or mass about which gathering, concentration, or accretion takes place."  However, `ParticleNucleus` is actually a spread out collection of nucleons based on their energy levels.  I realize that it's hard to get completely away from the term "nucleus" since that's the only place where nucleons tend to hang out together, so how about something like "LayeredNucleus", "SchematicNucleus", or "ExpandedNucleus"?  Feel free to insert "Particle" if you feel it's necessary, i.e. "LayeredParticleNucleus".

**Comment by zepumph** [comment]
Thanks @jbphet. We are in agreement! We would like to rename this to 

`ShellModelNucleus`. And in the view we have a `NucleonShellView` for each particle type, and that flows pretty well together.

**Comment by zepumph** [comment]
Working on this now.
