### ISSUE TITLE
Investigate getting rid of Particle.dragEndedEmitter and using userControlledProperty

### ISSUE THREAD

**Issue by zepumph** [phetsims/build-a-nucleus#184]
Promoting TODO to an issues:

https://github.com/phetsims/shred/blob/76e22d4925401076224e20ea7342c741cf12d8bf/js/model/Particle.ts#L56-L60

**Comment by zepumph** [comment]
From #165

**Comment by zepumph** [comment]
Well that was really easy! @Luisav1 will you please spot check the code and just play with the dragging in the sim a bit before closing. Everything looked good on my end.

**Comment by Luisav1** [comment]
It's looking great on my end too! Closing.
