### ISSUE TITLE
Memory Leak: AlphaParticle is not disposed because model.particleAnimations holds onto alphaParticleEmissionAnimation

### ISSUE THREAD

**Issue by zepumph** [phetsims/build-a-nucleus#186]
After the finishEmitter, we should be able to clear this and dispose this animation fully so that it releases the AlphaParticle. We also probably want to try to release that animation too.

Ideas:

Add a listener to an Animation.finishEmitter so that when done, we remove it from particleAnimations. Make sure to handle other lists if needed though.

**Comment by zepumph** [comment]
Tagging #119

**Comment by zepumph** [comment]
From https://github.com/phetsims/build-a-nucleus/issues/165

**Comment by zepumph** [comment]
@Luisav1 can you give this a spot check and feel free to close.

**Comment by Luisav1** [comment]
This is looking great, thanks. Closing.
