### ISSUE TITLE
Symbol Node and Available Decays panel bounds not updating properly

### ISSUE THREAD

**Issue by Luisav1** [phetsims/build-a-nucleus#187]
While working on https://github.com/phetsims/build-a-nucleus/issues/178, @zepumph and I found that the bounds of the Available Decays panel and of the Symbol node weirdly change when the locale changes dynamically.

For example, this is when the sim is loaded with `strings=long`. The symbol node pushes its bounds to the left, making the margin between nodes a bit small.
![image](https://github.com/phetsims/build-a-nucleus/assets/52978048/ba5e1e8f-2ac6-42c8-8869-c0ca2fc183fc)

And when the locale is dynamically changed, the panels are no longer right-aligned and the Symbol node pushes its bounds to the right.
![image](https://github.com/phetsims/build-a-nucleus/assets/52978048/d274485d-1f9f-48a7-98b8-a5ab644b41bd)

@ariel-phet Is this something we wanted to work on to fix?

**Comment by ariel-phet** [comment]
@Luisav1 @zepumph my suggestion would be to not worry about this issue and mark it deferred. It is pretty minor, and in no way should block publication as it seems like it might take a fair bit of effort to fix.

However, I would leave it as an open issue, that could potentially be tackled or rechecked at some point in the future.

**Comment by zepumph** [comment]
If your thoughts are that someone should do it at some point, then I'll definitely just go in now and just change the couple of maxWidths to even this out, especially while the code is fresh. It won't take long. No need to have such a small thing looming for years

**Comment by zepumph** [comment]
Just needed to tweak one maxWidth for the SymbolAccordionBox:

![image](https://github.com/phetsims/build-a-nucleus/assets/6856943/1c2d4081-bc2c-4286-9c59-67bc0ec2326d)

![image](https://github.com/phetsims/build-a-nucleus/assets/6856943/43f7d203-f814-45dd-b9b1-ac13c2bca67b)
