### ISSUE TITLE
Symbol panel doesn't reopen after Reset All 

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/build-a-nucleus#19]
**Test device**
MacBook Air (m1 chip)

**Operating System**
macOS 12.4

**Browser**
safari

**Problem description**
For https://github.com/phetsims/qa/issues/809

The Symbol accordion panel doesn't  reopen after pressing the Reset All button

**Steps to reproduce**
1. Close the Symbol panel
2. Press Reset All button

**Visuals**

https://user-images.githubusercontent.com/87318828/172448481-660fe674-8220-49b9-909d-052de46fb631.mp4

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Build a Nucleus‬
URL: https://phet-dev.colorado.edu/html/build-a-nucleus/1.0.0-betaDecay.11/phet/build-a-nucleus_all_phet.html
Version: 1.0.0-betaDecay.11 2022-06-04 01:06:50 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.61 Safari/537.36
Language: en-US
Window: 1365x694
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by Luisav1** [comment]
Thanks @Nancy-Salpepi! This was fixed in the above commit. Closing.

**Comment by Nancy-Salpepi** [comment]
I just took a quick look on Master and yes, it is fixed.
