### ISSUE TITLE
Consider rewording "Most likely decay"

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/build-a-nucleus#191]
For https://github.com/phetsims/qa/issues/977, in the second scene on the Chart Intro screen, I feel there could be potential confusion with the current wording "Most likely decay". 

I feel "Most likely decay (100%)"  could be interpreted by students to mean: There is a 100% chance that the isotope will decay. Adding the word "mode" after decay makes it really clear:
       -Most likely decay mode (100%)
       -Probable decay mode (100%)

**Comment by Luisav1** [comment]
@ariel-phet and I thought of 'Most likely decay type' or 'Probable decay type'. But will run this through by Jason to double-check.

**Comment by Luisav1** [comment]
Running through it by Jason, he said "'Most likely decay type' sounds better to me.  'Most likely decay path' might also work."

Will go with 'Most likely decay type'.

**Comment by Luisav1** [comment]
Reworded 'Most likely decay' to 'Most likely decay type' in the commit above. Closing.
