### ISSUE TITLE
slight overlap with stringTest=dynamic

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/build-a-nucleus#192]
**Test device**
MacBook Air M1 chip

**Operating System**
13.5.1

**Browser**
Safari 16.6

**Problem description**
For https://github.com/phetsims/qa/issues/977, with stringTest=dynamic, the Reset All button and Electron Cloud checkbox touch areas slightly overlap.

**Visuals**
<img width="474" alt="Screenshot 2023-09-13 at 8 18 56 PM" src="https://github.com/phetsims/build-a-nucleus/assets/87318828/d85cfaa3-ec2f-4856-8d03-2df3e25f5c79">

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: Build a NucleusBuild a Nucleus
URL: https://phet-dev.colorado.edu/html/build-a-nucleus/1.0.0-dev.23/phet/build-a-nucleus_all_phet.html?stringTest=dynamic&showPointerAreas
Version: 1.0.0-dev.23 2023-09-12 15:57:17 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Safari/605.1.15
Language: en-US
Window: 1317x706
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by zepumph** [comment]
@Luisav1 will take the lead making the the text maxWidth a bit smaller. We want a small margin between the two.

**Comment by Luisav1** [comment]
Thanks @Nancy-Salpepi! This was fixed in the commit above. Closing.
