### ISSUE TITLE
Remove old unused branches

### ISSUE THREAD

**Issue by zepumph** [phetsims/build-a-nucleus#199]
I see `buildANucleusDeprecated` and `betaDecay` branches. Do we need these anymore?

**Comment by Luisav1** [comment]
@zepumph I believe these branches should have been deleted when these issues were closed: #7 for `buildANucleusDeprecated` and #16 for `betaDecay`. Where do you see these? Thanks!

**Comment by zepumph** [comment]
Aha! I see they are only local for me, not on github. Oops. I'll delete me copies of these. Sorry for the bother.
