### ISSUE TITLE
Merge files from Luisav1/build-a-nucleus into phetsims/build-an-atom

### ISSUE THREAD

**Issue by chrisklus** [phetsims/build-a-nucleus#2]
All of the code changes to build-an-atom to make it run as build-a-nucleus will happen over in build-an-atom since BuildAnAtomModel and AtomScreenView were used to create build-a-nucleus.

We will use this issue to commit these changes to, as well as lay out the merging that needs to happen for each file.

**Comment by Luisav1** [comment]
### Build a Nucleus - changes to do

- [x] build-an-atom-strings_en.json
- added nucleus strings

- [x] js/buildanatom/view/view/PeriodicTableAndSymbol.js
- change symbol width proportion (smaller), and symbol font size (smaller)
- can be handled w option

- [x] js/symbol/view/SymbolNode.js
- Removed charge display and scale image, added isotope naming notation
- changed symbol box width (smaller), height (smaller), and font (bigger)
- base class for symbol text and child classes w options for mass + charge or isotope text, and option for symbol box size and font

- [x] New file
- js/buildanatom/view/NuclideChart.js (based on PeriodicTableAndSymbol.js)

- [x] js/common/view/AtomView.js - BAAScreenView.js
- removed unused Build an Atom strings, added nuclide strings and spacing constant
- removed electrons (font, width, group tandem, length, radio buttons orbits/cloud) and ions ('show' property, 
- add NuclideChart, nuclide chart accordion box, full nuclide chart button
- changed modelViewTransform - smaller width
- removed particleCountDisplay and added particleAtomDisplay (small nucleus at the top)
- removed Neutral/Ion and Element option from labelVisibilityControlPanel ('Show' on screen), thus change constant numDividerLines
- changed layout so buckets and chart button move w diff lang's
- added options

- [x] js/buildanatom/view/BuildAnAtomView.js - AtomScreenView.js
- remove mass number and charge (strings, accordion box), add symbol box (SymbolNode.js) in accordion box
- add this.nuclideChartAccordionBox in navigation order
- SUGGESTION: new class - NucleusScreenView.js

- [x] js/common/model/BuildAnAtomModel.js
- remove electrons (const's, bucket, array) and neutralOrIon property; remove their externally visible constants
	- kept electronShellDepictionProperty
- changed neutron num (less), bucket positions, particle capture condition
- SUGGESTION: use options but if messy can revaluate or more flexible w parent

**Comment by Luisav1** [comment]
@chrisklus and I think this was fixed in the commits above and is no longer applicable. Closing.
