### ISSUE TITLE
Electron Cloud checkbox doesn't reset to default 

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/build-a-nucleus#20]
**Test device**
MacBook Air (m1 chip)

**Operating System**
macOS 12.4

**Browser**
safari

**Problem description**
For https://github.com/phetsims/qa/issues/809, the 'Electron Cloud' checkbox isn't checked after pressing the Reset All button.

**Steps to reproduce**
1. Uncheck the 'Electron Cloud' checkbox
2. Press the Reset All button

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Build a Nucleus‬
URL: https://phet-dev.colorado.edu/html/build-a-nucleus/1.0.0-betaDecay.11/phet/build-a-nucleus_all_phet.html
Version: 1.0.0-betaDecay.11 2022-06-04 01:06:50 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.61 Safari/537.36
Language: en-US
Window: 1365x694
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by KatieWoe** [comment]
Visual:
![electronreset](https://user-images.githubusercontent.com/41024075/173137145-5de2e3be-bee9-44f0-ba5d-c5fcdf849ba4.gif)

**Comment by Nancy-Salpepi** [comment]
Just checked this on Master while confirming https://github.com/phetsims/build-a-nucleus/issues/19 and this also looked fixed @Luisav1!

**Comment by Luisav1** [comment]
This was fixed in the commit above, I forgot to close it. Thanks for checking @Nancy-Salpepi! Closing.
