### ISSUE TITLE
Graph color reconsideration

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/build-a-nucleus#203]
**Test device**
Samsung
**Operating System**
Win 11
**Browser**
Firefox
**Problem description**
For https://github.com/phetsims/qa/issues/988
Is it just me, or are the colors for B- and B+ decay a bit too similar? I can tell them apart on the graph easily enough, but on the legend they are smaller and/or further apart and a bit hard to distinguish.

**Visuals**
![image](https://github.com/phetsims/build-a-nucleus/assets/41024075/9cdec1d2-a628-4e04-8e19-8d367c951cf8)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Build a Nucleus‬
URL: https://phet-dev.colorado.edu/html/build-a-nucleus/1.1.0-rc.1/phet/build-a-nucleus_all_phet.html
Version: 1.1.0-rc.1 2023-09-26 23:04:02 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/118.0
Language: en-US
Window: 1536x731
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (ANGLE (Intel, Intel(R) HD Graphics Direct3D11 vs_5_0 ps_5_0))
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by marlitas** [comment]
(Unsolicited two cents) Just wanted to mention my colorblindness concern. They seem to blend in this particular case:

<img width="564" alt="image" src="https://github.com/phetsims/build-a-nucleus/assets/42476338/dd094a5e-878b-4724-9e57-b92009fcbcf0">

**Comment by ariel-phet** [comment]
@KatieWoe @marlitas we were balancing two goals here:

1. the B- and B+ decay were requested to be similar in hue (to suggest they were similar levels of instability)

2. Being reasonable for colorblindness. For this particular goal, I spent a significant amount of time playing with different combinations that would work reasonably for various color blind scenarios. When you have a visual like this chart with 6 colors, it is quite difficult to find a color combo that works for all situations (and still keeps two colors "close"). My understanding is that as long as there is some visual difference, people with color blindness are more attuned to being able to see the difference, and especially if there is a perceptible difference when in monochrome you are in a reasonable space.

Appreciate the attention to detail, but I am fairly confident in this particular case we have struck the best balance possible. 

In this case of legend we could play with perhaps play with the stroke around the legend if we feel that would help disambiguation (it might be that no stroke, or a different color stroke could make the difference in color larger for certain color blind cases).

**Comment by zepumph** [comment]
Sounds like this is ready for review and potentially closing if no one else has any thoughts. @KatieWoe @marlitas?

**Comment by marlitas** [comment]
That totally makes sense and does seem like a really hard balance @ariel-phet. Thanks for explaining and addressing my totally unnecessary concern. :-)

**Comment by KatieWoe** [comment]
Sounds good to me.
