### ISSUE TITLE
Should strings on buttons be vertically centered?

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/build-a-nucleus#205]
**Test device**
Samsung
**Operating System**
Win 11
**Browser**
Firefox
**Problem description**
For https://github.com/phetsims/qa/issues/988
If strings are long on buttons, they go towards the bottom of the button rather than staying vertically centered.

**Visuals**
![notcentered](https://github.com/phetsims/build-a-nucleus/assets/41024075/da452aa1-5e3d-4be4-ba03-f1e4c7ce4b08)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Build a Nucleus‬:‪Build a Nucleus‬
URL: https://phet-dev.colorado.edu/html/build-a-nucleus/1.1.0-rc.1/phet/build-a-nucleus_all_phet.html?stringTest=double
Version: 1.1.0-rc.1 2023-09-26 23:04:02 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/118.0
Language: en-US
Window: 1536x731
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (ANGLE (Intel, Intel(R) HD Graphics Direct3D11 vs_5_0 ps_5_0))
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by Luisav1** [comment]
Thanks @KatieWoe, this issue is the same as #50 where we decided that this small tradeoff with the proton/neutron emission decays sitting low is worth it so the beta decays are correctly center-aligned. Happy to discuss though if you have any other thoughts!
Feel free to close this if you agree with this decision.

**Comment by zepumph** [comment]
Yeah, centering vertically causes some challenges. Ready to close.
