### ISSUE TITLE
Text shifts with FF

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/build-a-nucleus#207]
**Test device**
Dell

**Operating System**
Win10

**Browser**
FireFox

**Problem description**
For https://github.com/phetsims/qa/issues/988, the periodic table shifts when I add/remove particles. 
I know this is a common thing for FF, but wanted it on the record.  

**Visuals**

https://github.com/phetsims/build-a-nucleus/assets/87318828/68883c18-1c53-4892-99bc-1a94ab0c2e62

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Build a Nucleus‬
URL: https://phet-dev.colorado.edu/html/build-a-nucleus/1.1.0-rc.1/phet/build-a-nucleus_all_phet.html
Version: 1.1.0-rc.1 2023-09-26 23:04:02 UTC
Features missing: applicationcache, applicationcache, touch
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
Language: en-US
Window: 1609x946
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by Luisav1** [comment]
@zepumph will take a look at some scenery options to fix this.

**Comment by zepumph** [comment]
Good catch @Nancy-Salpepi, there is a bit shift because the highlighted cell's lineWidth pushes things around by going outside of the other cell bounds. I committed above and cherry picked. Ready to review in next RC spot check, unassigning.  Feel free to close if all is good to go.

**Comment by Nancy-Salpepi** [comment]
This looks good to me with mac+ FF and Win10 + FF in rc.2
