### ISSUE TITLE
Should O-25 show neutron emission?

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/build-a-nucleus#209]
For https://github.com/phetsims/qa/issues/988, the decay screen says that O-25 doesn't form. According to website, https://www-nds.iaea.org/relnsd/vcharthtml/VChartHTML.html, it undergoes neutron emission. I currently don't have access to the 'ground truth data doc' to see what that says. 

<img width="138" alt="Screenshot 2023-10-09 at 2 00 55 PM" src="https://github.com/phetsims/build-a-nucleus/assets/87318828/f60e136c-6c3e-4869-9fd1-5a9b6d3f5808">

**Comment by Luisav1** [comment]
Yes, O-25 should exist. It is missing in the Nuclide data doc but it should be there.

**Comment by Luisav1** [comment]
Thanks @Nancy-Salpepi, in the above commit, O-25 was now added to the data tables in `AtomIdentifier` and appears as a neutron emission since that is it's only decay. It's half-life is unknown. This data for O-25 was also added to the Nuclide Data table doc. Closing.
