### ISSUE TITLE
Fuzz errors with parameters

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/build-a-nucleus#212]
**Test device**
Samsung
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/994. Found while testing https://github.com/phetsims/build-a-nucleus/issues/202.
I ran a fuzz test on the debug version with chartIntroScreenNeutrons and chartIntroScreenProtons and got these errors, though it didn't freeze the sim.

**Visuals**
![fuzzerror](https://github.com/phetsims/build-a-nucleus/assets/41024075/0d7b4995-abdb-4601-91f9-e032b4c929b8)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Build a Nucleus‬
URL: https://phet-dev.colorado.edu/html/build-a-nucleus/1.1.0-rc.2/phet/build-a-nucleus_all_phet.html
Version: 1.1.0-rc.2 2023-10-12 21:48:01 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
Language: en-US
Window: 1536x707
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by Luisav1** [comment]
Fuzzing locally with the same query query parameters (`http://localhost:8080/build-a-nucleus/build-a-nucleus_en.html?brand=phet&ea&debugger&chartIntroScreenProtons=2&chartIntroScreenNeutrons=2&fuzz`) I get these two other assertion errors quite quickly:
![image](https://github.com/phetsims/build-a-nucleus/assets/52978048/b89082af-93f6-4869-bfbb-55a830cc4feb)
![image](https://github.com/phetsims/build-a-nucleus/assets/52978048/01936d8a-ff69-4dfb-8211-47410b8f4653)

**Comment by zepumph** [comment]
The problems here were caused by https://github.com/phetsims/build-a-nucleus/issues/202. I recommend closing this issue as a duplicate. "Cannot fire while already firing" is a classic example of a downstream assertion. The very first assertion in @KatieWoe's console is most likely "should not be called if disposed". Let's pick this up over in https://github.com/phetsims/build-a-nucleus/issues/202
