### ISSUE TITLE
Update screenshots

### ISSUE THREAD

**Issue by zepumph** [phetsims/build-a-nucleus#213]
From the publication steps in the main checklist.

**Comment by zepumph** [comment]
@Nancy-Salpepi can you help us out with these?

**Comment by Nancy-Salpepi** [comment]
Sure. Just going to touch base with @arouinfar on the process.

**Comment by Nancy-Salpepi** [comment]
Screenshots uploaded to assets folder with the assistance of @KatieWoe.

**Comment by zepumph** [comment]
Excellent! I'll proceed with a cherry pick and republication. Thanks so much!

**Comment by zepumph** [comment]
Hello! After discussing with @arouinfar, @Nancy-Salpepi could you please also add screen-specific screenshots (using the `?screens` query parameter). Looks like it is expected to follow these instructions:

https://github.com/phetsims/website/issues/1322#issuecomment-1010320827

But I wonder if we should update the QA book screenshot doc to include this so that all screenshot-creating material is in one spot.

**Comment by Nancy-Salpepi** [comment]
Screen-specific screenshots were added to assets folder (as well as one additional screenshot for the website in a future deployment).

I updated the QA book as well. 

Anything else @zepumph or can we close?
