### ISSUE TITLE
Dynamic locale doesn't localize element name

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/build-a-nucleus#215]
This was reported by our Polish translator, but it appears to affect all locales.

Elements are translated properly in the [Polish version of the sim](https://phet.colorado.edu/sims/html/build-a-nucleus/latest/build-a-nucleus_pl.html), but not [the all version](https://phet.colorado.edu/sims/html/build-a-nucleus/latest/build-a-nucleus_all.html)(after dynamically switching locale).
![image](https://github.com/phetsims/build-a-nucleus/assets/5090275/35f31e01-4a61-4176-b352-f810f005613b)

May be related to https://github.com/phetsims/build-a-nucleus/issues/125 https://github.com/phetsims/build-a-nucleus/issues/90

**Comment by zepumph** [comment]
Thanks for reporting, and I'm sorry it took me so long to get to this. It looks like I totally omitted supporting dynamic locale with ShredStrings. It was easy enough to implement above, and now we can MR it into BAN 1.1. Thanks for your patience.

**Comment by zepumph** [comment]
QA: The bug was that the element name/identifier for a nuclide was not supporting dynamic local. You can see the bug here:

https://phet.colorado.edu/sims/html/build-a-nucleus/1.1.0/build-a-nucleus_all.html

Please make sure that switching the locale from the preferences menu updates the element name as well. Feel free to close.

**Comment by Nancy-Salpepi** [comment]
This looks fixed in 1.1.1-rc.1. Closing.

**Comment by zepumph** [comment]
@oliver-phet this is fixed  in https://phet.colorado.edu/sims/html/build-a-nucleus/1.1.1/build-a-nucleus_all.html, but please note that caching will not show the update for 24 hours:

https://phet.colorado.edu/sims/html/build-a-nucleus/latest/build-a-nucleus_all.html

Please let the user know. Thanks.

**Comment by oliver-phet** [comment]
Thanks, translator notified!
