### ISSUE TITLE
Broken link to Full chart

### ISSUE THREAD

**Issue by zepumph** [phetsims/build-a-nucleus#219]
I noticed today that this link isn't working. @Luisav1 do you want to investigate?

https://energyeducation.ca/simulations/nuclear/nuclidechart.html

**Comment by zepumph** [comment]
```
nuclidechart.html:365 Uncaught 
ReferenceError: nuclides is not defined
    at initChart (nuclidechart.html:365:2)
    at initialize (nuclidechart.html:321:2)
    at nuclidechart.html:1607:2

**Comment by Luisav1** [comment]
Thanks for the info! The issue was that the data script wasn’t being read correctly, causing `nuclides` to be undefined. Adding a header to `getnuclidesnew.php` to specify its content as JavaScript fixed it. Closing.
