### ISSUE TITLE
Wording of "Chemical reaction duration" is confusing

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/build-a-nucleus#22]
**Test device**
Dell
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/809.
In the half-life timescale, "C - Chemical reaction duration" is a bit confusing to me. My first thought is on a macro scale. For instance, if you mix baking soda and vinegar, how long do you see the reaction continue. This depends on a number of things such as amount of material and can vary wildly. The actual meaning is clearly on micro scale, looking at only one instance of the reaction. I'm wondering if there is a more clear way to word this entry.

**Visuals**
<img width="691" alt="cweird" src="https://user-images.githubusercontent.com/41024075/172494815-63f90a45-c4c5-4b82-bfe1-fd441a2c37e0.png">

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Build a Nucleus‬
URL: https://phet-dev.colorado.edu/html/build-a-nucleus/1.0.0-betaDecay.11/phet/build-a-nucleus_all_phet.html
Version: 1.0.0-betaDecay.11 2022-06-04 01:06:50 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36
Language: en-US
Window: 1280x649
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by Luisav1** [comment]
Possible changes:
- A millionth of a billionth of a second
- Time for light to cross 1000 atoms

Thanks!

**Comment by Luisav1** [comment]
My advisor said that the British billion is different than the American billion. So we @ariel-phet @chrisklus were thinking of going with "Time for light to cross 1000 atoms" for now.

**Comment by Luisav1** [comment]
Design meeting 2022-06-23

There are options to translate dialects however to avoid the confusion of the meaning of a billionth (and a millionth) that could exist in other languages it would be easier to go with 'time for light to cross 1000 atoms' for now. There is also currently already a pattern with 'time for light to ...' so it is easier to follow that. Since the difference in size of an atom and 1000 atoms is not really known to everyone, it would be good if eventually we could find some something that is the length of 1000 atoms.

**Comment by Luisav1** [comment]
Thanks @KatieWoe! This should be fixed in the commit above. Closing.
