### ISSUE TITLE
Screen doesn't pan consistently

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/build-a-nucleus#23]
**Test device**
MacBook Air (m1 chip)

**Operating System**
macOS 12.4

**Browser**
Safari

**Problem description**
For https://github.com/phetsims/qa/issues/809

The screen will pan when I remove a proton or neutron from the nucleus and drag it down, but doesn't pan when I grab a proton/neutron from the bottom of the play area and try to bring it towards the nucleus. 

**Steps to reproduce**
1. Zoom in so that the protons and neutrons at the bottom are visible, but the nucleus is not. 
2. Grab a proton and try to drag it towards the nucleus. --screen doesn't pan

**Visuals**

https://user-images.githubusercontent.com/87318828/172613005-740c4940-4563-429f-b3aa-b9f96578a2c1.mp4

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Build a Nucleus‬
URL: https://phet-dev.colorado.edu/html/build-a-nucleus/1.0.0-betaDecay.11/phet/build-a-nucleus_all_phet.html
Version: 1.0.0-betaDecay.11 2022-06-04 01:06:50 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.61 Safari/537.36
Language: en-US
Window: 1365x694
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by chrisklus** [comment]
Thanks @Nancy-Salpepi! This is likely related to https://github.com/phetsims/joist/issues/769, so @Luisav1 marked on hold for now.

**Comment by jessegreenberg** [comment]
Pan and zoom should be working better for this case after the above commit. Now the ParticleView is set as the drag target for the forwarded event. I think that is correct and the pan zoom listener can use that target to keep the element in view.

@Luisav1 @zepumph can you please confirm?

**Comment by zepumph** [comment]
Ahh yes, much better. Thank you for the help there. I really appreciate it.
