### ISSUE TITLE
Half-life rounding errors

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/build-a-nucleus#24]
For https://github.com/phetsims/qa/issues/809

Sometimes the half-life in the sim is rounded incorrectly. 
For example, Y-83 has a half life of 424.8 seconds. Rounding to 2 significant figures gives 4.2 x 10^2, but in the sim, it is 4.3 x 10^2. Another example is Y-85. 
<img width="550" alt="Screen Shot 2022-06-08 at 9 11 42 AM" src="https://user-images.githubusercontent.com/87318828/172625706-015973c2-705f-435b-97a0-54861b5ba642.png">
<img width="1031" alt="Screen Shot 2022-06-08 at 9 17 22 AM" src="https://user-images.githubusercontent.com/87318828/172626046-9ec119c3-8a12-4893-a951-e1e2bdb001a7.png">

**Comment by Luisav1** [comment]
@chrisklus suggested this is probably related to an issue in ScientificNotationNode. We will look into that.

Thanks!

**Comment by pixelzoom** [comment]
Definitely an issue in ScientificNotationNode, investigating in https://github.com/phetsims/scenery-phet/issues/747.

**Comment by pixelzoom** [comment]
Labeling this issue as blocks-sim-publication, since https://github.com/phetsims/scenery-phet/issues/747 is in-progress.

**Comment by pixelzoom** [comment]
@Luisav1 @chrisklus what is the priority of this issue, and when do you need it resolved? (https://github.com/phetsims/scenery-phet/issues/747 has turned into a real can of worms.)

**Comment by pixelzoom** [comment]
ScientificNotationNode has been greatly improved, and is ready for review in  https://github.com/phetsims/scenery-phet/issues/747.  It still exhibits some problems that are inherent in floating-point calculations. https://github.com/phetsims/scenery-phet/issues/747#issuecomment-1175229218 summarizes the remaining problems. In 6/30 dev meeting, @kathy-phet made the call that those problems are not blocking for build-a-nucleus, will not be addressed specifically for  ScientificNotationNode, and will eventually be investigated more generally (perhaps by looking at a library like math.js).

Let me know if you need anything else here.

**Comment by Luisav1** [comment]
Thanks @Nancy-Salpepi and @pixelzoom! @chrisklus, @marlitas and I just checked that the numbers are being rounded correctly now. Nancy could you review that it's working correctly now and close it if so?

**Comment by Nancy-Salpepi** [comment]
@Luisav1 the rounding twice error seems to have been fixed. I did find this one case though and I am wondering if there is an error in the spreadsheet? 
For 
<img width="345" alt="Screenshot 2022-10-28 at 3 06 58 PM" src="https://user-images.githubusercontent.com/87318828/198714827-4d669761-592e-48e4-8510-3be8efd286c6.png">
The sim says 3.0 x10^-2 instead of 3.1x10^-2. 

That is the only one I noticed, but obviously didn't try all of them.

**Comment by zepumph** [comment]
@Luisav1 and I investigated, and traced the above bug back to https://github.com/phetsims/scenery-phet/issues/613#issuecomment-1241264489. This is a known problem in common code, and not something that we are going to fix as part of this issue. Closing
