### ISSUE TITLE
Touch Areas Overlap

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/build-a-nucleus#26]
**Test device**
MacBook Air (m1 chip)

**Operating System**
macOS 12.4

**Browser**
Safari

**Problem description**
For https://github.com/phetsims/qa/issues/809

The touch areas for the number spinners look like they overlap. 

**Visuals**

<img width="527" alt="Screen Shot 2022-06-08 at 12 10 01 PM" src="https://user-images.githubusercontent.com/87318828/172666996-827b7815-c59e-4636-8230-939efd447d5b.png">

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Build a Nucleus‬
URL: https://phet-dev.colorado.edu/html/build-a-nucleus/1.0.0-betaDecay.11/phet/build-a-nucleus_all_phet.html
Version: 1.0.0-betaDecay.11 2022-06-04 01:06:50 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.61 Safari/537.36
Language: en-US
Window: 1365x694
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by Luisav1** [comment]
Thanks @Nancy-Salpepi! This is fixed in the commit above. You can go ahead and check it and close it if it is fixed.

**Comment by Nancy-Salpepi** [comment]
Looks fixed! Closing. 
<img width="981" alt="Screen Shot 2022-06-16 at 5 26 51 PM" src="https://user-images.githubusercontent.com/87318828/174168862-a6c042b0-29bc-4a2f-b9d9-46625139a3d8.png">
