### ISSUE TITLE
Should we indicate when decay mode is not represented or known?

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/build-a-nucleus#28]
For https://github.com/phetsims/qa/issues/809

When the half life is unknown, the sim clearly states that. However, when the decay mode is not represented/known, nothing is stated. I thought it would be more consistent to say something like 'Unstable: decay mode not represented/known'.  

_______
![half life](https://user-images.githubusercontent.com/87318828/172732940-6cbca9c2-ff10-46c7-83c3-fc677bd9caf5.JPG)
_______
![unstable](https://user-images.githubusercontent.com/87318828/172732960-13390eba-7a7d-47b4-a4de-6b84993cf67b.JPG)

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Build a Nucleus‬
URL: https://phet-dev.colorado.edu/html/build-a-nucleus/1.0.0-betaDecay.11/phet/build-a-nucleus_all_phet.html
Version: 1.0.0-betaDecay.11 2022-06-04 01:06:50 UTC
Features missing: applicationcache, applicationcache, touch
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36
Language: en-US
Window: 1273x578
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by Nancy-Salpepi** [comment]
Also I would also remove '(does not decay)' after 'stable.' As a teacher, I feel like we are giving away something students should be able to discover on their own.  
![stable](https://user-images.githubusercontent.com/87318828/172733541-9214f75d-98cd-4f97-8bfb-ce3dcd8fe6f2.PNG)

**Comment by ariel-phet** [comment]
This seems like a good discussion for a design meeting with @kathy-phet and @arouinfar also present. 

I believe the "(does not decay)" was a suggestion from @Luisav1 advisor, but we can definitely revisit this decision as a group.

We should also discuss the question of if/how to communicate to the user that the decay path is unknown.

**Comment by Luisav1** [comment]
Design meeting 2022-06-23

Will remove 'does not decay' because often that's something that needs to be discovered. That's a good recommendation.

To cover the cases of nuclides that are unstable and the decays are either not represented or not known, we will add an info button to the left of the 'Available Decays' title that will always be there. When clicked, a dialog would popup with a sentence or two that says something along the lines "You're getting shown the most common decay path(s), there can be other ones. In some cases there is no known decay path." The contents of the dialog would be static.

**Comment by Luisav1** [comment]
Reword info statement on decays:
"While other decays may exist, the available decays shown are the most common. In cases where there is no known decay, no available decays are shown."

**Comment by Luisav1** [comment]
Thanks for the suggestions @Nancy-Salpepi! We now have an info button in the decays panel with a statement on when decays are not represented or known. The '(does not decay)' part was also removed from 'Stable'. @Nancy-Salpepi You can close this if it's all good.

**Comment by Nancy-Salpepi** [comment]
Looks great @Luisav1! Just a quick question---was it an intentional design decision for the 2 info buttons to be different colors (I wasn't at that design meeting)?

**Comment by Luisav1** [comment]
Great question @Nancy-Salpepi, yes it was. We decided to have the decays info button be a lighter/more muted color that doesn't stand out as much so when someone is playing with the sim, clicking that button isn't the first thing they do. But if they see that all decay buttons are disabled then they may notice that decays info button and click it.

**Comment by Nancy-Salpepi** [comment]
Got it. Thanks!
