### ISSUE TITLE
Repo shows up in common code repos

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/build-a-nucleus#3]
From Slack:
>Kathryn Woessner  4:41 PM
I think build a nucleus might be a common code repo instead of a sim repo
Chris Klusendorf:spiral_calendar_pad:  4:42 PM
yeah i noticed that too! it’s marked as simulation: true in the package.json so i’m not sure what i did wrong, has this happened recently to other new sim repos?
Kathryn Woessner  4:43 PM
I think it's happened once or twice, but I don't remember the sim. I can look to see if we made an issue though
Kathryn Woessner  4:51 PM
I can't find the issue and I didn't see anything when I looked at the package.json that stood out to me. Sorry.

<img width="413" alt="commonrepo" src="https://user-images.githubusercontent.com/41024075/123178531-a077c300-d444-11eb-93e6-1d4829f18889.png">

**Comment by KatieWoe** [comment]
It seems to be in the right section this morning. Not sure what changed. Should we close, or still investigate?

**Comment by Luisav1** [comment]
The sim is now showing up under the sim repos. Closing.
