### ISSUE TITLE
Instances of being stuck on a non-forming nuclide

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/build-a-nucleus#30]
**Test device**
Dell
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/809. In the dev issue it says:
>Please look out for getting stuck in a frozen state. For example, an alpha decay on Beryllium - 6 (4 protons and 2 neutrons) results in Helium - 2 (2 protons and 0 neutrons), a nuclide that does not exist, so we handled that case separately.

I have found 2 other instances of this so far. If/as I find more I will add them. So far a Beta + decay from Ni-48 and Ni-49 have been found to cause this.

**Visuals**
![stuck](https://user-images.githubusercontent.com/41024075/172940482-aa753410-4c86-432c-87d4-050488f58736.gif)
<img width="959" alt="frozen2" src="https://user-images.githubusercontent.com/41024075/172940488-b6e1ad89-b9ed-4b6f-ab99-f18ad4871907.png">
<img width="960" alt="frozen1" src="https://user-images.githubusercontent.com/41024075/172940490-98360209-61cf-4ea1-8e07-d4a478f5052e.png">

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Build a Nucleus‬
URL: https://phet-dev.colorado.edu/html/build-a-nucleus/1.0.0-betaDecay.11/phet/build-a-nucleus_all_phet.html
Version: 1.0.0-betaDecay.11 2022-06-04 01:06:50 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36
Language: en-US
Window: 1280x649
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by KatieWoe** [comment]
Other instances found:
Ti-38 decaying by proton emission

Pr-121 may do this based on the chart, but I can't seem to make it in the first place to find out
<img width="960" alt="cantmake" src="https://user-images.githubusercontent.com/41024075/172943603-0a21a016-1ff9-4c8c-94ee-76db097a472d.png">

**Comment by KatieWoe** [comment]
This can be done with many nuclides when combined with multitouch.
1. Drag a neutron out and hold it to the side.
2. With other fingers/the buttons, create a nuclide that doesn't form
3. In the second the invalid nuclide is on screen, add the neutron from 1
4. As long as this is also an invalid nuclide, the sim will now be stuck

![morestuck](https://user-images.githubusercontent.com/41024075/173152180-8c851e3a-24ae-4c58-81ee-ecc3eb1e19a8.gif)

**Comment by Luisav1** [comment]
Possible ideas to get unstuck from this frozen state:

My advisor was considering to add to these special cases text that says "Area of active research". He suggested going back to the previous nuclide or leaving that nuclide that doesn't form up and re-enabling everything.

@ariel-phet suggested having an undo button to get out of this case where you get stuck on a nuclide because it feels odd to automatically undo a reaction that does happen because for others for example, trying to add a neutron where you can't - it just pops back out. @chrisklus thinks this might be good idea.

@ariel-phet suggests maybe having the button there permanently for nuclides where there are multiple decays so the user can explore all decay paths of a nuclide more easily.

Do we like the way it is? Should the undo button only appear on cases where you are stuck? or all the time? Are there any weird consequences? Would it be difficult to add the information of the last state of the sim to be able to undo?

**Comment by Luisav1** [comment]
Design meeting 2022-06-23

To get out of being stuck on a a non-forming nuclide we will add a yellow undo button like the one in Build a Fraction (`ReturnButton.js`).

The undo button would appear only after a decay button was clicked. It would be aligned to the left of the decay it would undo, outside the 'Available Decays' panel. It would keep track of only the last state of the sim but if anything in the nucleus changes, meaning nucleons are added or removed, then the last state would be wiped out and the undo button would disappear.

When the undo button is clicked, there would be an instantaneous change back to the last state of the sim, there wouldn't be an animation.

**Comment by Luisav1** [comment]
@ariel-phet happy with it it, will close.

**Comment by KatieWoe** [comment]
Reopening for a quick question for https://github.com/phetsims/qa/issues/823. Should cases like an alpha decay on Beryllium - 6 still handle themselves since this new method was implemented? It seems inconsistent that some cases take care of themselves and some don't.

**Comment by Luisav1** [comment]
@ariel-phet We should defer this for the moment, there is a bit of inconsistency here but it's best to discuss at design meeting: is there something special about Beryllium-6 with the 2 protons remaining? But it doesn't matter for the prototype publication.

**Comment by KatieWoe** [comment]
I don't think there is anything special about. Just that it, and maybe a few others were handled in the previous dev version by breaking apart or something similar, rather than the new fix.

**Comment by zepumph** [comment]
Discussed during design meeting today. We think of Beryllium-6 as a special case, but don't want to handle it any differently than the "does not form" case for the 2 remaining protons. We like this, and are ready to close.
