### ISSUE TITLE
Shaking text

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/build-a-nucleus#32]
**Test device**
Dell
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/809.
Sometimes, when a nuclide decays, when the emitted particle leaves the screen, the red text describing the isotope shakes. It doesn't do this with every emission, but the ones it does it on seem to be repeatable. I'm not sure what the connections are though. The example shown is F-21 to Ne-21 by Beta - decay.

**Visuals**
![jitter](https://user-images.githubusercontent.com/41024075/172955858-2ba78e2d-9412-4b35-b28b-9daef7267be7.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Build a Nucleus‬
URL: https://phet-dev.colorado.edu/html/build-a-nucleus/1.0.0-betaDecay.11/phet/build-a-nucleus_all_phet.html
Version: 1.0.0-betaDecay.11 2022-06-04 01:06:50 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36
Language: en-US
Window: 1280x649
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by Luisav1** [comment]
I couldn't reproduce this on Windows 10 Chrome. @chrisklus and I think that it's okay for this to happen for a prototype but we'll double check in design meeting.

We added the low priority label because this is a visual bug that seems to not be happening everywhere, and it's unlikely to cause anyone confusion. It wouldn't cause a pedagogical problem.

**Comment by KatieWoe** [comment]
I'm seeing this in https://github.com/phetsims/qa/issues/823, but for some reason it doesn't seem as bad, at least not with the example listed above.

**Comment by Luisav1** [comment]
@ariel-phet This wouldn't stop the prototype publication.

**Comment by KatieWoe** [comment]
I saw this in https://github.com/phetsims/qa/issues/828 and it could be fairly pronounced.
![jitter](https://user-images.githubusercontent.com/41024075/186983471-b333b8aa-47a2-42cd-8653-c8fbc64d3632.gif)

**Comment by Nancy-Salpepi** [comment]
I'm not able to reproduce this on mac + safari/chrome.

**Comment by zepumph** [comment]
@KatieWoe, we have redone some layout work recently in #90 to support dynamic locale. Both @Luisav1 and I cannot reproduce on master. Can you please try to and feel free to close if you cannot reproduce? Thanks!

**Comment by KatieWoe** [comment]
Wasn't able to see it on master. Closing, but may reopen if it comes back
