### ISSUE TITLE
Particle flashes at the edge of a screen

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/build-a-nucleus#33]
**Test device**
iPad 6th Gen
**Operating System**
iPadOS 15.5
**Browser**
Safari
**Problem description**
For https://github.com/phetsims/qa/issues/809
When picking up a proton or neutron in a tall window, such as an iPad in portrait mode, that particle flashes briefly at the bottom of the screen.
**Steps to reproduce**
1. Make sure the window is tall and narrow
2. Grab a proton or neutron with mouse or touch, not a button

**Visuals**

https://user-images.githubusercontent.com/41024075/173107102-8e734cd3-9987-4490-89d1-bd386354eae3.MOV

**Comment by KatieWoe** [comment]
If you drop the particle without moving it, the particle on the edge of the screen stays put and you can pick it up again.

https://user-images.githubusercontent.com/41024075/173143352-e4b09383-7e15-4fb1-88f2-52a72708c669.MOV

**Comment by Luisav1** [comment]
Thanks @KatieWoe! @chrisklus and I fixed this in the commit above but it'd be good if you could double check. You can also go ahead and close it if it is fixed.

**Comment by KatieWoe** [comment]
Looks good on master
