### ISSUE TITLE
Possible screenshot issue

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/build-a-nucleus#34]
For https://github.com/phetsims/qa/issues/809. This was found on iPadOS 15 while checking for https://github.com/phetsims/scenery/issues/1424. After taking the screenshot, which took awhile, I tried to interact with the sim. While the sim did not freeze, it did end up in the state bellow, and trying to use the reset all button did not solve this. I'm not sure how to reliably reproduce this.
![318E3565-DE97-4DC7-B0C9-2BAB46D47CCF](https://user-images.githubusercontent.com/41024075/173150967-7bf51660-7fa1-4f5f-b7d7-790433bd76bd.png)

**Comment by Luisav1** [comment]
@chrisklus and I will mark this on-old until https://github.com/phetsims/scenery/issues/1424 is fixed.

**Comment by zepumph** [comment]
https://github.com/phetsims/scenery/issues/1424 is fixed on master (just waiting on a potential MR). Closing
