### ISSUE TITLE
Positron node in available decays changes color

### ISSUE THREAD

**Issue by Luisav1** [phetsims/build-a-nucleus#35]
The positron node changes color from a dark gray-green to its normal bright green color after beta decay.

This is seen in the visual from https://github.com/phetsims/build-a-nucleus/issues/30, https://github.com/phetsims/build-a-nucleus/issues/30#issuecomment-1152743264 and https://github.com/phetsims/build-a-nucleus/issues/31#issue-1266709510.

**Comment by ariel-phet** [comment]
Self-assigning to see if I can reproduce

**Comment by Luisav1** [comment]
Not easily reproducible, wouldn't worry about it. @ariel-phet hasn't been able to reproduce it yet.

**Comment by ariel-phet** [comment]
I have tried reproducing this issue and have not seen it occur. Closing
