### ISSUE TITLE
Uneven font size in Half-life Timescale dialog

### ISSUE THREAD

**Issue by Luisav1** [phetsims/build-a-nucleus#38]
The text on the left side of the Half-life timescale is smaller then the right side. I suspect this to be due to changing the text for issue https://github.com/phetsims/build-a-nucleus/issues/22.

![image](https://user-images.githubusercontent.com/52978048/179054355-90860cbc-4cd1-4cd3-a313-6baddda743c5.png)

Need to fix it so both sides look equal.

**Comment by Luisav1** [comment]
Fixed in the commits above. Closing.

**Comment by Nancy-Salpepi** [comment]
@Luisav1 I see the uneven font size with stringTest=double for https://github.com/phetsims/qa/issues/823 (but I don't think that is something that affects publishing a prototype).
<img width="1005" alt="Screen Shot 2022-08-05 at 8 25 04 AM" src="https://user-images.githubusercontent.com/87318828/183078848-0974c9b4-0df6-4248-b059-c1cc57df7177.png">

**Comment by Luisav1** [comment]
Thanks @Nancy-Salpepi, this should be fixed in the commit above.

**Comment by Nancy-Salpepi** [comment]
For version 1.0.0-rc.8, font size is the same in both columns in the Half-life Timescale dialog with all string tests.
