### ISSUE TITLE
Issue organization for prototype publication

### ISSUE THREAD

**Issue by Luisav1** [phetsims/build-a-nucleus#39]
Organizing issues to be addressed from milestone https://github.com/phetsims/build-a-nucleus/milestone/1 for prototype publication.

#### Might not be able to address
- [x] https://github.com/phetsims/build-a-nucleus/issues/35
- [x] https://github.com/phetsims/build-a-nucleus/issues/36
#### Start
- [x] https://github.com/phetsims/build-a-nucleus/issues/38
- [x] https://github.com/phetsims/build-a-nucleus/issues/31 - found solution but complex

### Review
- [x] https://github.com/phetsims/build-a-nucleus/issues/30 - review with AP

**Comment by zepumph** [comment]
Prototype has been published. Closing
