### ISSUE TITLE
Should the nucleus decay while a nucleon is still being held?

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/build-a-nucleus#41]
**Test device**
MacBook Air (m1 chip)

**Operating System**
12.5

**Browser**
Safari

**Problem description**
For https://github.com/phetsims/qa/issues/823, when holding onto a neutron that results in an impossible nucleus, the nucleus decays while I am still holding the neutron. 

From slack:
[Nancy Salpepi](https://app.slack.com/team/U027AF93XE1)
  [6:14 PM](https://phetsims.slack.com/archives/D03JF82FC5D/p1659564841848449)
Hey Luisa! I was wondering if this behavior was correct….I saw it a couple of times when removing a neutron from the nucleus “manually”
Normally if I removed a neutron to create an impossible nucleus, when I let go, it went back to the nucleus. In this instance, it doesn’t give me the opportunity to let go before it decays into something else. I just wanted to make sure that was correct.

[Luisa Vargas](https://app.slack.com/team/U022HCYBGUE)
  [6:21 PM](https://phetsims.slack.com/archives/D03JF82FC5D/p1659565288815039)
Hey Nancy! I see, I think that has to do with a change we made where the nucleons that are being held are now part of the current nucleon count, causing the immediate decay. So I think this behaviour is expected but that is a valid question and maybe good issue to bring up since it didn't work that way previously with the other version. I would want to see what Ariel has to say about this.

**Visuals**

https://user-images.githubusercontent.com/87318828/182723788-b801961e-a03b-4550-a843-f8a346a3c49c.mp4

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Build a Nucleus‬
URL: https://phet-dev.colorado.edu/html/build-a-nucleus/1.0.0-dev.17/phet/build-a-nucleus_all_phet.html
Version: 1.0.0-dev.17 2022-08-02 23:09:01 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6 Safari/605.1.15
Language: en-US
Window: 1068x704
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by Nancy-Salpepi** [comment]
I just want to point out that the spontaneous decay doesn't alway happen.
For example, with calcium-34, if I pull a neutron out of the nucleus and hold on to it, it says "Calcium-33 does not form" but the nucleus doesn't spontaneously decay. 
This seems similar to the inconsistencies @KatieWoe was reporting in https://github.com/phetsims/build-a-nucleus/issues/30#issuecomment-1204178434

https://user-images.githubusercontent.com/87318828/182902139-e2604bdd-4b87-4c5e-8358-90fc1b67306b.mp4

**Comment by ariel-phet** [comment]
Marking to be discussed at design meeting.

Although there is some inconsistency here, it is happening with "held" nucleons which is more of an edge case and not typical use. This discussion should not hold up prototype publication

**Comment by Nancy-Salpepi** [comment]
@ariel-phet @Luisav1 I also wanted to point out that with the SAME nucleus, when I pull out a neutron the nucleus will sometimes spontaneously decay and sometimes not. For example, in this (very long) video, at the beginning, when I pull out a neutron, it says Iodine-107 doesn't form and spontaneously breaks down. Later in the video, when I pull out a neutron to create I-107, it says Iodine-107 doesn't form but doesn't break down.

https://user-images.githubusercontent.com/87318828/185989855-eec22a6b-b80e-43e9-a62d-819cc19b02dd.mp4

**Comment by zepumph** [comment]
From design meeting today. 

We were not able to reproduce the issue for 

http://localhost:8080/build-a-nucleus/build-a-nucleus_en.html?brand=phet&ea&debugger&protons=55&neutrons=57&screens=1

We only had the "nicer" behavior described in https://github.com/phetsims/build-a-nucleus/issues/41#issuecomment-1205483645

We are ready to close.
