### ISSUE TITLE
Sim shows decay mode for Ce-138

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/build-a-nucleus#43]
**Test device**
MacBook Air (m1 chip)

**Operating System**
12.5

**Browser**
Safari

**Problem description**
For https://github.com/phetsims/qa/issues/823, the sim shows that Ce-138 undergoes beta positive decay, but both the nuclide chart and data table show no known decay modes. 

**Visuals**
<img width="933" alt="Screen Shot 2022-08-04 at 2 14 02 PM" src="https://user-images.githubusercontent.com/87318828/182922414-48f76efa-9add-462d-b374-85931adf8958.png">

--

<img width="579" alt="Screen Shot 2022-08-04 at 2 19 27 PM" src="https://user-images.githubusercontent.com/87318828/182922672-c9116a99-3085-4d5d-8d6c-d68eead29914.png">

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Build a Nucleus‬
URL: https://phet-dev.colorado.edu/html/build-a-nucleus/1.0.0-dev.17/phet/build-a-nucleus_all_phet.html
Version: 1.0.0-dev.17 2022-08-02 23:09:01 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6 Safari/605.1.15
Language: en-US
Window: 1068x704
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by Nancy-Salpepi** [comment]
Same goes for Cr-50
<img width="579" alt="Screen Shot 2022-08-04 at 4 10 41 PM" src="https://user-images.githubusercontent.com/87318828/182943719-0e9d67df-fbf2-40b4-8079-31eb7f7cd4bc.png">

----
<img width="928" alt="Screen Shot 2022-08-04 at 4 12 49 PM" src="https://user-images.githubusercontent.com/87318828/182943879-8ee9a952-e094-43e7-ae79-a1d54074ebbe.png">

**Comment by Luisav1** [comment]
@ariel-phet this is a bug and should be fixed for the prototype.

**Comment by Luisav1** [comment]
Thanks @Nancy-Salpepi for catching this. This is an error on my part when editing that data table since in the original data both Cr-50 and Ce-138 undergo beta decays. Closing.
