### ISSUE TITLE
Should there be an indication of Uranium being the last buildable atom?

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/build-a-nucleus#44]
**Test device**
Dell
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/823
You can only build up to Uranium in the sim. Should this be indicated to the user?
From Slack:
> [Luisa Vargas]
  [11:33 AM]
Oh I think so, it could look like an error. I could add that to the focus and special instructions? We chose to not look at atoms higher than uranium is because we were only representing atoms that naturally occur in nature.

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Build a Nucleus‬
URL: https://phet-dev.colorado.edu/html/build-a-nucleus/1.0.0-dev.17/phet/build-a-nucleus_all_phet.html
Version: 1.0.0-dev.17 2022-08-02 23:09:01 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
Language: en-US
Window: 1280x649
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by Luisav1** [comment]
@ariel-phet To me the indication is that you run out of nucleons to add, but can consider other ideas in design meeting.

**Comment by zepumph** [comment]
Running out of available building nuclides seems reasonable (from design meeting today). Closing

**Comment by zepumph** [comment]
We do the same thing as charges and fields. You only "get" so many building blocks, so it feels quite natural to have this constraint built in.
