### ISSUE TITLE
Add the label "seconds" to the Half-Life Timescale

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/build-a-nucleus#45]
For https://github.com/phetsims/qa/issues/823, I think it would be nice if the timescale in the dialog also had the "seconds" label underneath it like in the play area. It would help make sense of things like the average human lifespan (10^9).

<img width="774" alt="Screen Shot 2022-08-05 at 1 54 56 PM" src="https://user-images.githubusercontent.com/87318828/183135091-ee1ab277-50ff-4c6c-a15d-66339d06aa32.png">

**Comment by Luisav1** [comment]
Thanks @Nancy-Salpepi, that's a great suggestion. We'll add the units.

**Comment by Luisav1** [comment]
Thanks @Nancy-Salpepi, this was fixed in the commits above.

**Comment by Nancy-Salpepi** [comment]
Looks good @Luisav1! Closing
