### ISSUE TITLE
Lag outside of play area

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/build-a-nucleus#47]
For https://github.com/phetsims/qa/issues/823. Seen on iPadOS 15.
I saw on the iPad that if a particle was flying off (such as an electron after B- decay) it would start to lag once it left the play area. Specifically, the area that would be present if the sim was in landscape is what I'm calling the play area. If the iPad is in portrait mode and the particle flies up or down into the large amount of whitespace, that is where I see the lag.

https://user-images.githubusercontent.com/41024075/184675599-fce533a2-d26f-4871-bc8a-53be9725ea5c.mov

**Comment by Luisav1** [comment]
@chrisklus and I looked at the code that emits a nucleon and found nothing that would cause a lag once a particle leaves the play area. Then checked the performance profile to see if we could find any BAN functions but only found this layout call in purple. We're not convinced that this is sim code that's causing the problem, it could be code in scenery instead. @jonathanolson have you seen an issue similar to this before? Note the stacks on the left side are when the particle is animating inside the dev bounds and the ones on right are when it leaves the dev bounds.
![image](https://user-images.githubusercontent.com/52978048/186962670-b30b8b35-a7a3-4582-9a14-be83372301e9.png)

**Comment by jonathanolson** [comment]
Interesting, that might be due to DOM operations. @jessegreenberg is it possible to run without any parallel DOM view for testing?

Additionally, can you try with the `preventFit: true` option on the ScreenView?

**Comment by Luisav1** [comment]
Thanks @jonathanolson, `preventFit: true` has fixed the problem. I'll leave this open to be verified in the next RC https://github.com/phetsims/qa/issues/828.

**Comment by jessegreenberg** [comment]
Also, I just verified this sim doesn't support Interactive Description, so there are no PDOMPeers or related HTML elements in the DOM.

**Comment by chrisklus** [comment]
For QA: Please close if this is fixed. Thanks!

**Comment by Nancy-Salpepi** [comment]
In 1.0.0-rc.10, I still see the particles sputtering a bit (even in the play area), but I think that is because my iPad is older. I am using an iPad air 2. However, the sputtering is significantly less than it was outside of the play area when comparing with an older version. 

https://user-images.githubusercontent.com/87318828/188955186-cda7eb2c-afb7-4181-a21d-4328686a7322.mov

**Comment by stemilymill** [comment]
https://github.com/phetsims/qa/issues/833

this seems to be improved but not totally fixed, and my observations are different than Nancy's

On my ipad (pro 10.5 inch) the only sign of lag I saw in dev.14 was the particle briefly freezing as it exited the play area. in the rc.10 version, the freezing is less noticeable and also only occurs when the particle is going up- when the particle exits the play area going downward, it continues without sputtering.

On Win10 Chrome (dell laptop) in dev.14 when a particle leaves the play area, various visual elements seem to vibrate up and down until the particle completely disappears. I did **NOT** observe any of this in rc.10.

**Comment by ariel-phet** [comment]
Although we should leave this issue open for further investigation, the behavior looks good enough for prototype publication.

**Comment by zepumph** [comment]
I investigated this a bit more, and could reproduce it with 6x slower CPU in the dev tools. It is a faint lag bug noticeable. I'm not really sure how to investigate this further, but I did put `preventFit` onto both screen views.

**Comment by zepumph** [comment]
After talking with JO, `preventFit` still feels like the best path forward. I'll mark this to see what QA thinks about it now.

**Comment by zepumph** [comment]
(Fingers crossed over here) QA feel free to close if all is good.

**Comment by KatieWoe** [comment]
I didn't see any lag on my iPad with this

**Comment by Nancy-Salpepi** [comment]
For https://github.com/phetsims/qa/issues/988
On my iPad (9th generation) with iOS 17 I am seeing some sputtering. It is more noticeable on the Chart intro Screen. It isn't unusable or anything, but thought I would let you know. 

https://github.com/phetsims/build-a-nucleus/assets/87318828/1bd5a6f1-8cf3-4068-907f-8f135699f5d8

**Comment by zepumph** [comment]
Given the amount of time spent on this issue, and the amount of UX concern it entails, I think we should reclose. I also feel like we are doing the best we can without substantial changes. Thanks for the report though!
