### ISSUE TITLE
Debug version doesn't load with Mac + Safari 

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/build-a-nucleus#48]
For https://github.com/phetsims/qa/issues/828 and possibly related to https://github.com/phetsims/number-play/issues/179, the DeBug version of the sim doesn't move past the splash screen with mac + safari. These errors appear in the console:

<img width="499" alt="Screen Shot 2022-08-22 at 3 38 21 PM" src="https://user-images.githubusercontent.com/87318828/186005584-9559ad5f-b9aa-46b8-ba11-a639a6c10a01.png">

With Mac + chrome, the Debug version does load. This is what the console looks like there:
<img width="349" alt="Screen Shot 2022-08-22 at 3 42 28 PM" src="https://user-images.githubusercontent.com/87318828/186005656-3514715d-8376-4577-bd64-58ecc91de1a7.png">

**Comment by KatieWoe** [comment]
Noting that it does seem to load on Win 11 Chrome

**Comment by Nancy-Salpepi** [comment]
Working in new version 1.0.0-rc.8 on Mac +safari
