### ISSUE TITLE
Small text sits low on buttons

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/build-a-nucleus#50]
**Test device**
Dell
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/828
When strings are double or long, they may get smaller, which is intended. However, when this happens on a button, the text seems lower on the button and no longer centered. This is likely a minor issue.

**Visuals**
<img width="133" alt="lowonbutton" src="https://user-images.githubusercontent.com/41024075/186989162-4a160bf1-06a6-41e9-a94a-94cf5e080ac5.png">

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Build a Nucleus‬
URL: https://phet-dev.colorado.edu/html/build-a-nucleus/1.0.0-rc.8/phet/build-a-nucleus_all_phet.html
Version: 1.0.0-rc.8 2022-08-25 22:49:47 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
Language: en-US
Window: 1280x649
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by Luisav1** [comment]
@ariel-phet This wouldn't stop prototype publication.
@chrisklus We will ask JO since he worked on layout.

**Comment by zepumph** [comment]
From discussion with @Luisav1, this is because we don't want to use the center of the text so that the symbols like beta are well aligned.

![image](https://github.com/phetsims/build-a-nucleus/assets/6856943/b2750bf7-ca41-445a-8498-dcd4907ad517)


@Luisav1 and I feel good not fixing this. It's a tradeoff that we are happy to discuss if anyone wants to reopen. Closing
