### ISSUE TITLE
Last nuclide may not appear

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/build-a-nucleus#51]
**Test device**
Samsung Chromebook and Dell
**Operating System**
ChromeOS and Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/828
The last of a nuclide (either proton or neutron) may not appear before it is added to the nucleus. This happens if you are adding them individually or both at once from lower numbers. You can still add the last ones with the buttons, but not by dragging.

**Visuals**
<img width="955" alt="237noneutron" src="https://user-images.githubusercontent.com/41024075/187284318-1754a680-426e-4618-b0aa-c5ead24273e3.png">

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Build a Nucleus‬
URL: https://phet-dev.colorado.edu/html/build-a-nucleus/1.0.0-rc.8/phet/build-a-nucleus_all_phet.html
Version: 1.0.0-rc.8 2022-08-25 22:49:47 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
Language: en-US
Window: 1280x649
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by KatieWoe** [comment]
Edit, should say last nuclide, not second to last.

**Comment by chrisklus** [comment]
Thanks @KatieWoe! @Luisav1 and I had some trouble fixing this initially - the problem was occurring because the total count of each nucleon was blipping to the max when it was one smaller than the max because they were being double counted momentarily when being moved from the "particles on their way to the atom" array into the atom itself.

When discussing with @ariel-phet, we had the idea to track these counts just based on "what is out in the play area", instead of worrying about where the nucleons specifically were when out in the play area. Turns out, we were already setup to do this nicely with the particles array on the BANModel.

@KatieWoe could you please confirm on phettest?

**Comment by KatieWoe** [comment]
This still seems to be happening on phettest.

**Comment by chrisklus** [comment]
@KatieWoe it's working on phettest for me, do you mind checking if it's a caching problem? thanks!

**Comment by KatieWoe** [comment]
It shouldn't be since I was in an incognito window, but I'll try one more time.

**Comment by KatieWoe** [comment]
Ok, it seems ok now, not sure why it wasn't working before, maybe I didn't pull correctly. Sorry about that.

**Comment by chrisklus** [comment]
For QA: Please close if this is fixed. Thanks!

**Comment by Nancy-Salpepi** [comment]
This looks good in 1.0.0-rc.10. Closing.

**Comment by Nancy-Salpepi** [comment]
Sorry I just saw this similar issue with mac + chrome/safari. After U-238 decays, the neutron disappears after a second but the arrow is still active and a neutron can be added. 

https://user-images.githubusercontent.com/87318828/188962345-aeecb1b4-0580-4531-b22e-64f9df25035d.mp4

**Comment by Luisav1** [comment]
Thanks @Nancy-Salpepi! @chrisklus and I ideally fixed this in the above commit. Could you please check? We also added the "protons=x" and "neutrons=x" query parameters that you can use to get to U-238 quickly.

**Comment by Nancy-Salpepi** [comment]
@Luisav1 @chrisklus I no longer see the neutron randomly disappearing 🎉  and I love the new proton= neutron = query parameters! Two things:
1. The decrease proton+neutron button size has shrunk
<img width="469" alt="Screen Shot 2022-09-15 at 8 01 20 AM" src="https://user-images.githubusercontent.com/87318828/190406205-d1231c70-e66f-4f9a-b375-1c31220cc14d.png">

2. There is a delay for the proton at the bottom to disappear when any of the Pa isotopes undergoes beta minus decay (and in the case of Pa-237 it takes a while for the last neutron to appear).

https://user-images.githubusercontent.com/87318828/190406762-aa320974-352b-4c8d-8c45-3b668ffaf113.mp4

**Comment by Luisav1** [comment]
Thanks @Nancy-Salpepi! @chrisklus and I refactored the way the creator node visibility is checked, which fixed the above cases but also changed a lot of other code. We would appreciate thorough testing again on the creator node visibility. Thanks again!

**Comment by Nancy-Salpepi** [comment]
@Luisav1 @chrisklus things are looking good to me. @KatieWoe is also going to take a look, so please hold off on closing.

**Comment by KatieWoe** [comment]
I didn't see anything on my end :)

**Comment by chrisklus** [comment]
Looks like this is good to close, thanks all!
