### ISSUE TITLE
No credits in the about dialog

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/build-a-nucleus#52]
**Test device**
Dell
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/828
The about dialog contains no credits. For QA, Nancy, Emily, and myself should be included.

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Build a Nucleus‬
URL: https://phet-dev.colorado.edu/html/build-a-nucleus/1.0.0-rc.8/phet/build-a-nucleus_all_phet.html
Version: 1.0.0-rc.8 2022-08-25 22:49:47 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
Language: en-US
Window: 1280x649
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by KatieWoe** [comment]
Clifford should be added as well.

**Comment by Luisav1** [comment]
@ariel-phet Could you provide the information for the credits? Thanks! Here's what I have so far, is there anything else we should add or anything to correct?
```
    leadDesign: 'Ariel Paul, Amy Rouinfar',
    softwareDevelopment: 'Chris Klusendorf, Luisa Vargas',
    team: 'Ariel Paul, Kathy Perkins',
    qualityAssurance: 'Clifford Hardin, Emily Miller, Nancy Salpepi, Kathryn Woessner',
    graphicArts: '',
    soundDesign: '',
    thanks: ''
```

**Comment by ariel-phet** [comment]
Hi Luisa,

You should be included in lead design and software development, and your name should probably be first on both.

Since some of your funding has come from Canadian sources it would likely be appropriate to thank them (really a question for Jason). See the credits dialogue in [Wave Interference](https://phet.colorado.edu/sims/html/wave-interference/latest/wave-interference_en.html) for an example of the kind of language we have used in the past, and probably consult with Jason about the correct language to put in this thanks section if he wants to acknowledge any funders.

Probably more like:
    leadDesign: 'Luisa Vargas, Ariel Paul`
    softwareDevelopment: 'Luisa Vargas, Chris Klusendorf',
    team: 'Jason Donev (University of Calgary), Kathy Perkins, Amy Rouinfar',
    qualityAssurance: 'Clifford Hardin, Emily Miller, Nancy Salpepi, Kathryn Woessner',
    graphicArts: '',
    soundDesign: '',
    thanks: ''

**Comment by chrisklus** [comment]
For QA: Please close if this is fixed. Thanks!

**Comment by Nancy-Salpepi** [comment]
The credits portion matches https://github.com/phetsims/build-a-nucleus/issues/52#issuecomment-1231959941 but no "Thanks" section was added. @Luisav1 @chrisklus was it decided that there wouldn't be one?

**Comment by Luisav1** [comment]
It wasn't decided yet, I've asked Jason and he hasn't heard back from our funders yet. If we do add a "Thanks" section, I was going to add it afterwards.

**Comment by chrisklus** [comment]
@Luisav1 committed a draft above - @ariel-phet suggested we make a small change to `We gratefully acknowledge the support of ECO Canada for helping to fund this sim.`
