### ISSUE TITLE
Add query parameters for setting the proton and neutron count when the sim starts

### ISSUE THREAD

**Issue by Luisav1** [phetsims/build-a-nucleus#57]
@chrisklus and I added these query parameters while working on https://github.com/phetsims/build-a-nucleus/issues/51 to make it easier to work on it.

My supervisor Jason and I talked about adding a way to control the nucleon counts with number inputs while the simulation is running, we may add that in the future later or instead of these query parameters.

**Comment by zepumph** [comment]
Initial implementation was done here, and a bug or two that has come up since will be addressed over in https://github.com/phetsims/build-a-nucleus/issues/84. Closing
