### ISSUE TITLE
Use VBox for contentNode in AvailableDecaysPanel

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/build-a-nucleus#63]
In order to replace HSeparatorDeprecated with HSeparator, and just "in general"...

AvailableDecaysPanel.ts should use a VBox for its contentNode.  VBox will handle the layout for you, as well as the resizing of the HSeparator.  It current uses a Node for contentNode, with a bunch of manual layout that duplicates what VBox will handle.

**Comment by jbphet** [comment]
I think this was put in the wrong repo, since `AvailableDecaysPanel` is a class in Build a Nucleus.  I will transfer.

**Comment by jbphet** [comment]
Assigning to @chrisklus in addition to @Luisav1, since they are the ones that are working on this sim.  Unassigning myself.

**Comment by Luisav1** [comment]
This was fixed in the commit above. Assigning to @marlitas for review.

**Comment by marlitas** [comment]
Added a couple review comments in the above commit. Small things. The changes look great!

**Comment by zepumph** [comment]
Comments addressed in https://github.com/phetsims/build-a-nucleus/commit/488f42179f8f5abfd166891e4be953c5f61c5594. Closing
