### ISSUE TITLE
Assignment to static fields in constructor

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/build-a-nucleus#64]
Related to https://github.com/phetsims/tandem/issues/278 ...

In BANScreenView.ts:

```typescript
  public static protonsCreatorNodeModelCenter: Vector2;
  public static neutronsCreatorNodeModelCenter: Vector2;
...
protected constructor( model: M, modelViewTransform: ModelViewTransform2, providedOptions?: BANScreenViewOptions ) {
...
    BANScreenView.protonsCreatorNodeModelCenter = this.modelViewTransform.viewToModelPosition( this.protonsCreatorNode.center );
    BANScreenView.neutronsCreatorNodeModelCenter = this.modelViewTransform.viewToModelPosition( this.neutronsCreatorNode.center );
```

In general, a constructor should not be setting a static field. This will happen every time that BANScreenView (or its subclasses) are instantiated.   Recommended to make `protonsCreatorNodeModelCenter` and `neutronsCreatorNodeModelCenter` non-static.

**Comment by marlitas** [comment]
This was fixed in the above commit. Closing.
