### ISSUE TITLE
Unnecessary use of ModelViewTransform in NucleonNumberLine (and HalfLifeNumberLineNode)

### ISSUE THREAD

**Issue by veillette** [phetsims/build-a-nucleus#69]
in `NucleonNumberLine.js`, a modelViewTransform and a chartTransform are defined.

```js
  let modelViewTransform: ModelViewTransform2;
    if ( orientation === Orientation.HORIZONTAL ) {
      modelViewTransform = ModelViewTransform2.createRectangleMapping(
        new Bounds2( modelXStartRange, 0, modelXEndRange, 1 ),
        new Bounds2( 0, 0, viewWidth, tickMarkLength )
      );
    }
    else {
      modelViewTransform = ModelViewTransform2.createRectangleMapping(
        new Bounds2( 0, modelXStartRange, 1, modelXEndRange ),
        new Bounds2( 0, 0, tickMarkLength, viewWidth )
      );
    }

    const numberLineNode = new Node();
    let chartTransform: ChartTransform;
    if ( orientation === Orientation.HORIZONTAL ) {
      chartTransform = new ChartTransform( {
        viewWidth: viewWidth,
        modelXRange: new Range( modelXStartRange, modelXEndRange )
      } );
    }
    else {
      chartTransform = new ChartTransform( {
        viewHeight: -viewWidth,
        modelYRange: new Range( modelXStartRange, modelXEndRange ),
        modelYRangeInverted: true
      } );
    }
```

The chartTransform is not limited to usages for the Bamboo library. The chartTransform has multiple methods such as `modelToViewX`, `modelToViewY`, etc, that can be used to position elements, which you could leverage here instead creating a superfluous ModelViewTransform2. 

I'll mention that it is also fine (and maybe less obfuscating) to use the tickMarkLength to position view elements rather than artificially creating a ModelViewTransform that set a unit of 1 to tickMarkLength. 

Assigning to @Luisav1

**Comment by veillette** [comment]
For instance you could use replace the previous use of the ModelViewTransform to position the label, by using the chartTransform

````js
    // create and add the tick labels
    const tickLabelSet = new TickLabelSet( chartTransform, orientation, tickXSpacing, {
      extent: 5,
      createLabel: ( value: number ) => new Text( value, {
        fontSize: 12,
        fill: Color.BLACK
      } ),
      positionLabel: ( label: Node, tickBounds: Bounds2, axisOrientation: Orientation ) => {
        if ( axisOrientation === Orientation.HORIZONTAL ) {

          // ticks flow horizontally, so tick labels should be below
          label.centerTop = tickBounds.centerBottom.plusXY( chartTransform.modelToViewDeltaX( -0.5 ), 1 );
        }
        else {

          // ticks flow vertically, so tick labels should be to the left
          label.rightCenter = tickBounds.leftCenter.plusXY( -1, chartTransform.modelToViewDeltaY( -0.5 ) );
        }
        return label;
      }
    } );
    numberLineNode.addChild( tickLabelSet );
````
Note that it is preferable to use the `modelToViewDeltaY` to `modelToViewY`, if you would like to do some relative positioning. It makes your code more robust ( rather than relying on the fact that the minY=0).
    
By the way I question the usage of the 1 and -1 in the positioning of the label above. These are view (and not model) coordinates so it is a very minute change in the position of the label.

**Comment by veillette** [comment]
There is a similar superfluous instance of `ModelViewTransform2` in `HalfLifeNumberLineNode.js`.  The chartTransform defined in `HalfLifeNumberLineNode` is sufficient to do all the mapping from the model to the view. I think it would need to be converted to a private instance ( instead of a local variable) for your purposes.

**Comment by veillette** [comment]
In the commit above, I removed the instance of `modelViewTransform` in `HalfLifeNumberLineNode`
```js
// TODO: Fix the view Y's
    this.modelViewTransform = ModelViewTransform2.createRectangleMapping(
      new Bounds2( NUMBER_LINE_START_EXPONENT, 0, NUMBER_LINE_END_EXPONENT, 1 ),
      new Bounds2( 0, 0, viewWidth, tickMarkLength )
    );
```

Instead I created a private readonly instance of 'chartTransform`
```js
  this.chartTransform = new ChartTransform( {
      viewWidth: options.numberLineWidth,
      modelXRange: new Range( NUMBER_LINE_START_EXPONENT, NUMBER_LINE_END_EXPONENT )
    } );
```

As a result, I replaced all the calls on modelViewTransform by chartTransform, such as the following

```diff
-      halfLifeArrow.translation = new Vector2( this.modelViewTransform.modelToViewX( xPosition ),
+     halfLifeArrow.translation = new Vector2( this.chartTransform.modelToViewX( xPosition ),
```

Assigning to @Luisav1 to check that this did not generate unintended changes, as well as review the changes. Feel free to close afterwards.

**Comment by Luisav1** [comment]
The changes look good, thanks @veillette! Closing.
