### ISSUE TITLE
Is it desirable for NucleonNumberLine to own its chartTransform?

### ISSUE THREAD

**Issue by veillette** [phetsims/build-a-nucleus#70]
I cant help but notice that we have an AccordionBox entitled Partial Nuclide Chart.

It seems to me that therefore the so called NucleonNumberLine is not really a number line but merely used as an axe of a chart that hasn't been implemented yet (correct me if i'm wrong)

In this case, wouldn't be preferable to create a chartTransform outside of NucleonNumberLine such as this

````js
    const  chartTransform new ChartTransform( {
        viewWidth: 250,
        viewHeight: 200,
        modelXRange: new Range( 0, 12 ),
        modelYRange: new Range( 0, 10 ),
        modelYRangeInverted: true
      } );
  ````

The chartTransform could then be used for the implementation of Partial Nuclide Chart.

This chartTransform could be passed in the constructor of NucleonNumberLine as well as the orientation. 

```js
 public constructor( chartTransform: ChartTransform, particleCountProperty: TReadOnlyProperty<number>, orientation: Orientation ) {
```
With this information, it would be enough to go about decorating the axis .

**Comment by veillette** [comment]
From the design document, I was able to confirm that indeed, the Partial Nuclide Chart is indeed a chart.
<img src="https://user-images.githubusercontent.com/7633344/211871283-7249eabf-b2ea-411c-8ccc-464bd55e8aff.png" width=250>


This implies that NucleonNumberLine should not create its own ChartTransform but  it should be passed to it in the constructor.

**Comment by veillette** [comment]
The commit in https://github.com/phetsims/build-a-nucleus/commit/2f12c73fe90abafde52d63e57873158996ea5509 moves out the chartTransform from the NucleonNumberLine.

**Comment by veillette** [comment]
The chartTransform instantiation has been changed.

```js
   const scaleFactor = 20;

    const chartTransform = new ChartTransform( {
      viewWidth: BANConstants.CHART_MAX_NUMBER_OF_NEUTRONS * scaleFactor,
      modelXRange: new Range( BANConstants.DEFAULT_INITIAL_NEUTRON_COUNT, BANConstants.CHART_MAX_NUMBER_OF_NEUTRONS ),
      viewHeight: BANConstants.CHART_MAX_NUMBER_OF_PROTONS * scaleFactor,
      modelYRange: new Range( BANConstants.DEFAULT_INITIAL_PROTON_COUNT, BANConstants.CHART_MAX_NUMBER_OF_PROTONS )
    } );
```

Two great aspect of the above changes is that 
- it gets rid of magic number and 
- it also enforces the isometry of the chart with a common scalingFactor for the x and y view units. 

However, it makes an (undesirable) assumption that the min value of the model ranges is zero. 

It may be preferable to change the chartTransform instantitation to 

```js
    const modelXRange = new Range( BANConstants.DEFAULT_INITIAL_NEUTRON_COUNT, BANConstants.CHART_MAX_NUMBER_OF_NEUTRONS );
    const modelYRange = new Range( BANConstants.DEFAULT_INITIAL_PROTON_COUNT, BANConstants.CHART_MAX_NUMBER_OF_PROTONS );

    // Scale to transform model to view coordinates.
    const scaleFactor = 20;

    const chartTransform = new ChartTransform( {
      viewWidth: modelXRange.getLength() * scaleFactor,
      modelXRange: modelXRange,
      viewHeight: modelYRange.getLength() * scaleFactor,
      modelYRange: modelYRange
    } );
```

Assigning to @Luisav1 to make the change

**Comment by Luisav1** [comment]
Thanks @veillette for the review! These issues were fixed in the commits above. Closing.
