### ISSUE TITLE
(Mini) Review of Model View Transforms

### ISSUE THREAD

**Issue by veillette** [phetsims/build-a-nucleus#73]
@marlitas stated:
> Overall the focus of the review should be on the Chart Intro Screen, specifically the play area including the NucleonShellView, NucleonCreatorNode, and ParticleNucleus. We used three Model View Transforms for the ChartIntroScreen. One to center the play area across screens, one to convert model coordinates to view coordinates, and one to place particles accurately within the screen.

Self-Assigning

**Comment by veillette** [comment]
As part of this review, in #69, I noted that the instantiation of a ModelViewTransform2 is unnecessary if you already have an equivalent ChartTransform.

**Comment by veillette** [comment]
There are three `ModelViewTransforms` used in `ChartIntroScreen`:

```js
    // mini-atom center
    const modelViewTransform = ModelViewTransform2.createSinglePointScaleMapping(
      Vector2.ZERO,
      new Vector2( BANConstants.SCREEN_VIEW_ATOM_CENTER_X, 87 ),
      1.0 );

      // centers particle atoms on energy levels
      particleViewMVT: ModelViewTransform2.createSinglePointScaleMapping( Vector2.ZERO,
        new Vector2( 135, 193 - BANConstants.PARTICLE_RADIUS ), 1.0 ) // top left corner of proton energy levels 

  // the MVT that places nucleons in their individual array positions
  NUCLEON_ENERGY_LEVEL_ARRAY_MVT: ModelViewTransform2.createRectangleInvertedYMapping( new Bounds2( 0, 0, 5, 2 ),
    new Bounds2( 0, 0, ( PARTICLE_RADIUS * 2 ) * 5, ( PARTICLE_RADIUS * 2 ) * 10 ) )
```

The last one is used in `NucleonShellView` and `ParticleNucleus`.   

A few comments:

Unlike projectile motion, or pendulum lab, there is no natural physical mapping between the model and the view. This is why in your case, two of the model view transform have a scale factor of 1.  It points to the fact that this particular simulation does not have a need per say for ModelViewTransforms. In other words, having a ModelViewTranform is a simulation is not a sine qua none requirements. 
I was able to parse easily what you are doing in the code and it is easy to read.  At the same time, it could be done  without any kind of ModelViewTransforms.
The conclusion from all of this is a question I put to you:

_Do you feel that the ModelViewTransforms is useful for your purposes, do you feel empower by mvt,  in the sense that it makes your development easier, or do you feel that you have a false sense of obligation to use a ModelViewTransform and are you continually frustrated by its usages._

Depending on the answer to the above question, you may choose to keep it the ModelViewTransforms or you can jettison them and make all the positioning with view coordinates.   

If you do keep NUCLEON_ENERGY_LEVEL_ARRAY_MVT , then it should be better documented as I could not fathom why you do this particular mapping. 

A side note: There is a real convenience to have a mapping from model to view in NumberLines/AxisLines or Charts in general. As I commented in #69, the particular usage of ModelViewTransform is redundant because the model to view mapping is contained in a ChartTransform. Although  I wasn't asked to review their usages in `NucleonNumberLine` and `HalfLifeNumberLineNode` , their are the most problematic ones.

**Comment by veillette** [comment]
Assigning back to @marlitas, and @Luisav1.

Let me know if you have any questions.

**Comment by veillette** [comment]
@Luisav1 : In the commit above, instead of using 
`ModelViewTransform2.createSinglePointScaleMapping( Vector2.ZERO, Vector2.ZERO, 1 )` , you can use `ModelViewTransform2.createIdentity()`..

`ModelViewTransform2.createIdentity()` is useful to use when you have common code components that require a modelViewTransform as a parameter, but you would rather not use one.

**Comment by Luisav1** [comment]
Thanks @veillette! I fixed that in the commit above.

**Comment by zepumph** [comment]
@Luisav1 looked over the remaining usages of ModelViewTransform2 and all looked good. We were able to pull out a single usage for the ParticleNodes too. Closing
