### ISSUE TITLE
error TS2339: Property 'incomingProtonsNumber' does not exist on type 'ParticleNucleus'.

### ISSUE THREAD

**Issue by samreid** [phetsims/build-a-nucleus#75]
CT Saw this issue: 

```
error TS2339: Property 'incomingProtonsNumber' does not exist on type 'ParticleNucleus'.
```

I'll comment it out for now.

**Comment by samreid** [comment]
OK I commented it out for now, @Luisav1 and @marlitas can you please look for a longer-term solution?

**Comment by marlitas** [comment]
Addressing now.

**Comment by marlitas** [comment]
This was vestigial from some properties we removed. Should be fixed now.
