### ISSUE TITLE
Rename "proton/neutron count" variables to "number"

### ISSUE THREAD

**Issue by samreid** [phetsims/build-a-nucleus#77]
While working on https://github.com/phetsims/build-a-nucleus/issues/46, @Luisav1 and I saw that many places in the code refer to "Proton Count" or "Neutron Count" while the user interface consistently refers to them as "Proton Number" and "Neutron Number".  We would like to rename variables in the code to use "number" to match the user interface.

**Comment by zepumph** [comment]
@Luisav1 will take the lead here. Let me know if you run into any trouble.

**Comment by Luisav1** [comment]
I renamed all variables with the "count" suffix to have the "number" suffix, except for the protonCountProperty / neutronCountProperty / nucleonCountProperty variables since those come from shred's ParticleAtom. Closing.
