### ISSUE TITLE
Remove color coding from periodic table

### ISSUE THREAD

**Issue by Luisav1** [phetsims/build-a-nucleus#79]
The highlighting of cells in the periodic table is confusing as it highlights it using pink, the same colour of the neutron emission decay in the `PartialNuclideChart`. 
To correct this, @marlitas, @ariel-phet, and I initially thought of having the highlight colour be the same as the current decay colour, using the legend from the `PartialNuclideChart`.
However, since the periodic table only represents the elements and not any nuclides, it should not indicate any type of possible decay. Therefore, we concluded that to highlight your current element, the background colour will be removed from the symbol node in the `PeriodicTableNode` and the `PeriodicTableCell` will be highlight only by bolding the font in the cell.

**Comment by Luisav1** [comment]
@marlitas and I thought that the highlighting of the current element only using the stroke color was a bit too subtle so we tried inverting the cell text color and background color. @ariel-phet what do you think between these options or do you have any other suggestions we should try? We can chat about it during our next design meeting as well.
![image](https://github.com/phetsims/build-a-nucleus/assets/52978048/e19b6855-5ae8-4cf7-8df3-e8b768f92199)
![image](https://github.com/phetsims/build-a-nucleus/assets/52978048/8525bbb8-a029-4bf0-b1cc-748c7f6d5a4f)

**Comment by ariel-phet** [comment]
After discussing, I definitely agree that the reverse contrast option is quite nice.

**Comment by Luisav1** [comment]
@marlitas and I applied the changes and it's looking good with the reverse contrast. Closing.
