### ISSUE TITLE
Decay equation implementation

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/build-a-nucleus#80]
Try some different mockups with the equation above the zoomed in chart.

**Comment by ariel-phet** [comment]
<img width="424" alt="zoomed chart 1" src="https://github.com/phetsims/build-a-nucleus/assets/4051174/03193b19-30e6-4586-b5a8-a69d080506ce">
<img width="428" alt="zoomed chart 2" src="https://github.com/phetsims/build-a-nucleus/assets/4051174/0fc82240-d121-4af0-832a-0b3f0ba8cddb">

<img width="284" alt="zoomed chart 3" src="https://github.com/phetsims/build-a-nucleus/assets/4051174/80ff7e54-ff2b-42eb-a3e8-707984cbb403">

**Comment by Luisav1** [comment]
Will go with the first version for now.

**Comment by Luisav1** [comment]
**Design meeting 7/5:**

- [x] What if there's no cell node, what's the DecayEquationNode representation?
            Leave the equation space, but make it blank.
            Keep the "Most likely decay" but hide the parenthetical percentage
- [x] What if the nuclide is stable? Should anything show?
          Swap out the equation for the word "Stable"
        Keep the "Most likely decay" but hide the parenthetical percentage
- [x] What if the decay percentage is null ("unknown")?
       we like a space after the unknown word
- [x] Unknown decay cases?
       two possibilities: 1. use the word "Unknown" like for "Stable" case. 2 Use "Unknown" only on the right ride of the equation.
       Will go with case 2 for now
- [x] mostLikelyDecay string font size should match legend

**Design meeting 7/13:**
- [x] Make the arrow and the plus sign black instead of blue.
- [x] Left align the decay equation with the left side of the zoomed in chart grid.


**Design meeting 7/20:**
- [ ] Center align the decay equation on the zoomed in chart only when 'stable' is shown

**Comment by zepumph** [comment]
First implementation of the decay equation for the zoomed in chart is above. Here is a screenshot of the NOT pixel polished prototype:

![image](https://github.com/phetsims/build-a-nucleus/assets/6856943/c14d1ceb-061e-420a-ab5d-78a80cb60cbc)

**Comment by zepumph** [comment]
From a design meeting today:

- [x] Let's use a different class from SymbolNode so that the numbers are bigger and closer together. 
- [x] Decay button should be bigger.

**Comment by zepumph** [comment]
@Luisav1 and I worked on some of the items from our discussion with @ariel-phet today, but not everything. @Luisav1 will take the lead from here.

**Comment by zepumph** [comment]
Current look, we still have a few more items to go, 
![image](https://github.com/phetsims/build-a-nucleus/assets/6856943/b68f9630-3777-46d8-9424-6bfd535e25ee)

**Comment by Luisav1** [comment]
Current look after going through all the items from design meetings:
![image](https://github.com/phetsims/build-a-nucleus/assets/52978048/406bec5f-cb64-4355-bbe8-4d5be331c05d)

**Comment by zepumph** [comment]
- [x] From design meeting today. We need to remove the title arrow, and make the equation arrow match the white one used in the chart view.

**Comment by zepumph** [comment]
- [x] Center the "Stable" text over the zoomed in chart

**Comment by zepumph** [comment]
The chart arrow is variable length depending on where in the chart the decay will take you, so I tried to pick a length that felt good compared to all possibilities:

![image](https://github.com/phetsims/build-a-nucleus/assets/6856943/3a51d371-b13a-4378-92c5-da5b5eea198a)
![image](https://github.com/phetsims/build-a-nucleus/assets/6856943/d6a5e513-4f43-471a-9cb5-1614d474a63e)

**Comment by zepumph** [comment]
Ok I think we are good to go here. 

- [x] @Luisav1 will you give me a spot check about how the stable text is being positioned via a parameter now? 
- [x] @ariel-phet how do you feel about the arrow look now?

**Comment by ariel-phet** [comment]
@zepumph I think the arrow looks great!

**Comment by zepumph** [comment]
Excellent thanks. @Luisav1 feel free to close after spot check.

**Comment by Luisav1** [comment]
Thanks @zepumph, it's all looking good to me. Closing.
