### ISSUE TITLE
Completing Color Profile

### ISSUE THREAD

**Issue by Luisav1** [phetsims/build-a-nucleus#83]
Will focus on adding color properties in the nuclide chart to complete design of color scheme for nuclide chart. Such that @ariel-phet is not blocked.

**Comment by Luisav1** [comment]
@ariel-phet the color profiling of the chart and the sim is ready to go for your testing. The color profiling of the energy levels (https://github.com/phetsims/build-a-nucleus/issues/85) and of some of other parts of the sim are not supported but if you'd like it to be, we'd be happy to add that, just let us know.

**Comment by ariel-phet** [comment]
@Luisav1 @zepumph lets go with the following colors for the Chart/Magic numbers (tested all these carefully with all the various color blind tests, and they show contrast in all cases) These colors also fulfill Jason's feedback that the Beta minus/plus decays should seems a similar hue when compared to the stable color. Listed in (R,G,B) format

- buildANucleus.protonEmissionColor  (247,2,92)
- buildANucleus.neutronEmissionColor (255,31,255)
- buildANucleus.betaPlusColor (133, 202, 255)
- buildANucleus.betaMinusColor (148, 245, 245)
- buildANucleus.alphaColor (40,215,86)
- buildANucleus.nuclideChartBorderMagicNumberColor (251,255,36)

**Comment by zepumph** [comment]
Excellent. Committed above. Thanks @ariel-phet. Closing

<details>


![image](https://github.com/phetsims/build-a-nucleus/assets/6856943/c6a746ac-bd6e-4126-a326-5b703127dc0d)


![image](https://github.com/phetsims/build-a-nucleus/assets/6856943/ef41afb8-a804-4b9c-80fc-a0958d774e79)
