### ISSUE TITLE
Use Color.interpolateRGBA() for energy level colors in NucleonShellView

### ISSUE THREAD

**Issue by Luisav1** [phetsims/build-a-nucleus#85]
Use Color.interpolateRGBA() where you set the stroke of energy levels in NucleonShellView instead of having a manually calculated array of a range of colors. Such that only the initial and final color properties of the energy levels are needed.
Change link on nucleonCountProperty to multilink that also listens to when the initial + final color properties change.

**Comment by zepumph** [comment]
Working on this now.

**Comment by zepumph** [comment]
Tagging https://github.com/phetsims/shred/commit/84a635ee0f2110d1930ef707cf03d86e2b0b8fd7 as the original commit where the manual interpolation was committed.

https://github.com/phetsims/shred/blob/e5d99a25c55e21f061dba057a6299c47bb12e6f5/js/view/ParticleNode.ts#L28-L36
https://github.com/phetsims/shred/blob/c09eb9f1d2ee3f00c88fea61fc479d60d9a9f9cb/js/model/ParticleAtom.ts#L40-L48

**Comment by zepumph** [comment]
- [ ] Don't forget about Nucleon shell view

**Comment by zepumph** [comment]
Ok. Good progress for ParticleNode above. Now onto Nucleon shell view.

**Comment by zepumph** [comment]
Ok Good progress on ParticleNode above, now onto NucleonShellView.

**Comment by zepumph** [comment]
Ok. This has all been simplified. @Luisav1 will you please give these commits a spot check and feel free to close.

**Comment by Luisav1** [comment]
Thanks @zepumph, this looks great. Closing.

**Comment by Luisav1** [comment]
I noticed there's still a TODO pointing to this issue:
https://github.com/phetsims/build-a-nucleus/blob/d123a18112ec3b78b8948ceffe6415291741a3a3/js/common/view/ParticleAtomNode.ts#L165-L168
This similar code is also in these two other places:
- the initial creation of the electron cloud:
https://github.com/phetsims/build-a-nucleus/blob/d123a18112ec3b78b8948ceffe6415291741a3a3/js/common/view/ParticleAtomNode.ts#L47-L49
- the mini electron cloud creation
https://github.com/phetsims/build-a-nucleus/blob/d123a18112ec3b78b8948ceffe6415291741a3a3/js/decay/view/DecayScreenView.ts#L196-L198

**Comment by zepumph** [comment]
@Luisav1 and I would like to ignore and delete the TODO, and the just factor out the `new RadialGradient` code into BANConstants, where the function takes a radius and returns the gradient. We aren't worried about creating multiple of the gradients, as we don't want to mutate the radius after creating a the Gradient. Also recreating these is fine for the Color Editor, and still allows you to see the changes if you want to update the `electronColor`

**Comment by Luisav1** [comment]
The TODO was removed in the commit above and the RadialGradient is now created in BANConstants. Closing.
