### ISSUE TITLE
Implement "Magic Numbers" feature

### ISSUE THREAD

**Issue by zepumph** [phetsims/build-a-nucleus#87]
Expanding from https://github.com/phetsims/build-a-nucleus/issues/61 and https://github.com/phetsims/build-a-nucleus/issues/46

**Comment by zepumph** [comment]
From design meeting during 7/13. We would like to be a bit more subtle than the thick line in https://energyeducation.ca/simulations/build-a-nucleus/build-a-nucleus_en.html.

We like having something simple, with thicker lines and not special highlighting. @ariel-phet would like to mockup before we implement anything. Over to him.

**Comment by Luisav1** [comment]
From meeting with @ariel-phet 7/20, we decided to try and add a checkbox which would increase the stroke width of those cells who have magic numbers. Maybe we might need another class too such that we can play with that stroke width live.

**Comment by zepumph** [comment]
Also, if we can prep for Thursday with a potential ability to play around with the style of the stroke live, that would be great. Perhaps making the borders thicker, or dashed, or a different color (etc). I'll take the lead.

**Comment by zepumph** [comment]
A couple of potentially talking points for next design:


Same color, thicker line width:
![image](https://github.com/phetsims/build-a-nucleus/assets/6856943/191a4a7e-ac64-4af3-9392-0a78b7353cf6)

Slightly darker color:
![image](https://github.com/phetsims/build-a-nucleus/assets/6856943/3573c2b6-0ca9-423a-886c-2a8443208828)

Just for fun, a gradient:
![image](https://github.com/phetsims/build-a-nucleus/assets/6856943/befe30be-14ec-45a9-bb76-aa4734e74d94)



There is another color profile Property to play with if you want to before design meeting:

`nuclideChartBorderMagicNumberColorProperty`

Ready for review.

**Comment by zepumph** [comment]
- [x] This should also effect the zoomed in chart too.

**Comment by zepumph** [comment]
And for the zoomed-in view:
![image](https://github.com/phetsims/build-a-nucleus/assets/6856943/cf76a0b8-e809-4440-b619-fe45fe56ff98)

**Comment by zepumph** [comment]
Today in design meeting, we made the color Yellow, like a highlight. From here @ariel-phet will confirm the perfect color in correlation with #83. Over to him.

**Comment by ariel-phet** [comment]
@zepumph @Luisav1 

Since I worked on the colors in https://github.com/phetsims/build-a-nucleus/issues/83 I think once those are implemented, this issue will be good to go.

**Comment by zepumph** [comment]
Implemented above. See https://github.com/phetsims/build-a-nucleus/issues/83#issuecomment-1658664677
