### ISSUE TITLE
Should this sim support dynamic locale? 

### ISSUE THREAD

**Issue by zepumph** [phetsims/build-a-nucleus#89]
@kathy-phet can you weigh in on if this sim should support the dynamic locale feature?

**Comment by kathy-phet** [comment]
Yes. Thanks.

**Comment by kathy-phet** [comment]
And is it typescript ?

**Comment by zepumph** [comment]
Yes it is, but shred (the atom-based common code library) is not.

**Comment by zepumph** [comment]
See https://github.com/phetsims/build-a-nucleus/issues/90
