### ISSUE TITLE
Should interviews happen?

### ISSUE THREAD

**Issue by Luisav1** [phetsims/build-a-nucleus#92]
As we're almost feature-complete now, scheduling interviews might be important, if we decide to do them.
In https://github.com/phetsims/build-a-nucleus/issues/21, we left on leaving it up to interviews or prototype feedback to address the issue or not.

**Comment by ariel-phet** [comment]
This is a call for @kathy-phet -- please bring up at status meeting @zepumph

**Comment by zepumph** [comment]
We decided previously that we will want interviews.

@kathy-phet, I'm going to assign to you to make sure the right people are in charge of this.

**Comment by zepumph** [comment]
From slack @arouinfar will be scheduling these. Thanks!

**Comment by kathy-phet** [comment]
Yep Amy! I'm going to unassign myself.

**Comment by zepumph** [comment]
Excellent! Thanks @arouinfar. Please create new issues for any items that you think need work from the interviews.
