### ISSUE TITLE
Implement Alt-Input

### ISSUE THREAD

**Issue by zepumph** [phetsims/build-a-nucleus#96]
I believe that @kathy-phet would like us to do turn on basic keyboard navigation here. Let's see how it goes!

**Comment by zepumph** [comment]
Basic tab order was implemented above. I'll wait to do any more work until I hear some instruction. I only spent about 15 minutes on this issue thus far.

**Comment by zepumph** [comment]
Just a ping on this one @kathy-phet. I'm unsure how to proceed. It would be nice to confirm with a designer on PDOM order, but otherwise it is pretty straight forward (so long as we dont make individual particles grab/draggable).

**Comment by zepumph** [comment]
- [x] magic numbers checkbox and full chart view should be before the reset all button

**Comment by kathy-phet** [comment]
@arouinfar - Could you review the Alt-Input order for this sim as an emergent issue?

**Comment by arouinfar** [comment]
I reviewed dev.20 and the focus order looks good to me. The sim still needs a Keyboard Help dialog, though. I didn't notice any specialized interactions, so the "Basic Actions" common section will suffice. Here's an example from Geometric Optics: Basics.

<img width="706" alt="image" src="https://github.com/phetsims/build-a-nucleus/assets/8419308/280434d0-6ebc-4613-a9f1-ac0482dcfd8f">

**Comment by Luisav1** [comment]
From the code review #112.
- [x]  Is Node.pdomOrder used appropriately to maintain visual and PDOM layout balance?

**Comment by zepumph** [comment]
>Is Node.pdomOrder used appropriately to maintain visual and PDOM layout balance?
 
I just took one more look here, and this all looks good to me. Closing.

**Comment by zepumph** [comment]
We forgot that interactive highlights is part of alt input these days. Over in https://github.com/phetsims/build-a-nucleus/issues/161 I'll remedy this.
